/- Historical scope: any result after the Principia.
Results after Hypatia and before the Principia belong in BarrowLib; earlier
classical results belong in ClassicsLib. Chronology concerns the mathematical
result, not the date of its Lean encoding. Use of these results makes a
downstream historical proof anachronical, including use through its types.
Pre-Principia Chinese results go to ClassicsLib; Arabic results in the
post-Hypatia, pre-Principia window go to BarrowLib.
AI-derived results are modern only when their mathematics uses modern support.
Borrowed results must retain their exact original-language source passage;
formalization authorship does not establish discovery or historical dating. -/

import ModernLib.Comparison.CircleCompare
import ModernLib.Diagnostic.ConstructedHarmonicPotential
import ModernLib.Diagnostic.DeflectionPotential
import ModernLib.Diagnostic.InverseCubeAreal
import ModernLib.Diagnostic.PhaseArea
import ModernLib.Diagnostic.QuadraticEndpointPotential
import ModernLib.Foundation.Polygon.AffineBoundary
import ModernLib.Foundation.Polygon.AffineValues
import ModernLib.Foundation.Polygon.BinaryCells
import ModernLib.Foundation.Polygon.BinaryEndpoints
import ModernLib.Foundation.Polygon.BinaryLift
import ModernLib.Foundation.Polygon.BinaryTime
import ModernLib.Foundation.Polygon.BoundedCuts
import ModernLib.Foundation.Polygon.CalibrationCompletion
import ModernLib.Foundation.Polygon.CauchyValues
import ModernLib.Foundation.Polygon.CompletionGeometry
import ModernLib.Foundation.Polygon.ConvexValues
import ModernLib.Foundation.Polygon.CurveTrace
import ModernLib.Foundation.Polygon.DyadicNodes
import ModernLib.Foundation.Polygon.EndpointCauchyName
import ModernLib.Foundation.Polygon.FanValues
import ModernLib.Foundation.Polygon.FiniteAddress
import ModernLib.Foundation.Polygon.GeometricApproximation
import ModernLib.Foundation.Polygon.IntegerTime
import ModernLib.Foundation.Polygon.MatchedRegion
import ModernLib.Foundation.Polygon.MonotoneRectangles
import ModernLib.Foundation.Polygon.PairingValues
import ModernLib.Foundation.Polygon.PolygonValues
import ModernLib.Foundation.Polygon.PositionValues
import ModernLib.Foundation.Polygon.QuadraticPotentialValues
import ModernLib.Foundation.Polygon.QuadraticSecants
import ModernLib.Foundation.Polygon.RationalEnclosure
import ModernLib.Foundation.Polygon.SampledValues
import ModernLib.Foundation.Polygon.ScalarOrder
import ModernLib.Foundation.Polygon.ScaledTolerance
import ModernLib.Foundation.Polygon.SecantValues
import ModernLib.Foundation.Polygon.SquareContentValues
import ModernLib.Foundation.Polygon.SquareOuterContent
import ModernLib.Foundation.Polygon.SupportingBoundary
import ModernLib.Foundation.Polygon.SweptArea
import ModernLib.Foundation.Polygon.TailValues
import ModernLib.Foundation.Polygon.TangentTriangleValues
import BarrowLib.Common.Quadratic
import BarrowLib.Common.RationalMagnitudes
import ModernLib.Polygon.CalibratedForces
import ModernLib.Polygon.CauchyValues
import BarrowLib.Polygon.CentralSchedule
import ModernLib.Polygon.CompletedForce
import ModernLib.Polygon.Contact
import ModernLib.Polygon.Converse
import ModernLib.Polygon.Enclosure
import ClassicsLib.Euclid.FiniteLattice
import ModernLib.Polygon.ForceClasses
import ModernLib.Polygon.GeneralForceAccelerationSecants
import ModernLib.Polygon.GeneralForceArea
import ModernLib.Polygon.GeneralForceEndpoint
import ModernLib.Polygon.GeneralForceGrowth
import ModernLib.Polygon.GeneralForcePathContent
import ModernLib.Polygon.GeneralForcePathRegion
import ModernLib.Polygon.GeneralForcePolygonCurve
import ModernLib.Polygon.GeneralForcePrecision
import ModernLib.Polygon.GeneralForcePrefix
import ModernLib.Polygon.GeneralForceQuadraticSecants
import ModernLib.Polygon.GeneralForceSecants
import ModernLib.Polygon.GeneralForceTangentTriangle
import ModernLib.Polygon.GeneralForceTime
import ModernLib.Polygon.GivenMotionComparison
import ModernLib.Polygon.GivenTrajectoryArea
import ModernLib.Polygon.HarmonicAccelerationSecants
import ModernLib.Polygon.HarmonicAccumulation
import ModernLib.Polygon.HarmonicBinaryPrefix
import ModernLib.Polygon.HarmonicComparison
import ModernLib.Polygon.HarmonicCompletedForce
import ModernLib.Polygon.HarmonicConstructionAgreement
import ModernLib.Polygon.HarmonicCover
import ModernLib.Polygon.HarmonicDyadic
import ModernLib.Polygon.HarmonicDyadicAgreement
import ModernLib.Polygon.HarmonicGeneralEndpoint
import ModernLib.Polygon.HarmonicGeneralPathContent
import ModernLib.Polygon.HarmonicGeneralPolygon
import ModernLib.Polygon.HarmonicGeneralTime
import ModernLib.Polygon.HarmonicIntegerSubdivision
import ModernLib.Polygon.HarmonicPathContent
import ModernLib.Polygon.HarmonicPathRegion
import ModernLib.Polygon.HarmonicPolygonCurve
import ModernLib.Polygon.HarmonicQuadraticSecants
import ModernLib.Polygon.HarmonicRefinement
import ModernLib.Polygon.HarmonicSecants
import ModernLib.Polygon.HarmonicStability
import ModernLib.Polygon.HarmonicTimeComparison
import ModernLib.Polygon.HarmonicTimeRealization
import ModernLib.Polygon.HarmonicUniform
import BarrowLib.Polygon.ImpulseComposition
import ModernLib.Polygon.InertialControl
import ModernLib.Polygon.InertialDefect
import ModernLib.Polygon.MonotoneEnclosure
import ModernLib.Polygon.ParallelQuadraticEndpoint
import ModernLib.Polygon.PartialCell
import ModernLib.Polygon.PartitionComparison
import ModernLib.Polygon.PartitionControl
import ModernLib.Polygon.PathDefect
import ModernLib.Polygon.PositionValues
import ModernLib.Polygon.RefinementStrip
import ModernLib.Polygon.RegionConfinement
import ModernLib.Polygon.RelativeMotion
import ModernLib.Polygon.StripArea
import BarrowLib.Polygon.TimeSubdivision
import ModernLib.Polygon.UniformRefinement
import ModernLib.Polygon.ZeroForce
import ModernLib.Reconstruction.MonotoneRectangles
import ModernLib.Reconstruction.SupportingBoundary
