import NewtonLimitDynamics

-- Generated; compile with lake env lean research/CheckReferences.lean.
#check DeMotu1684.QuadraticInitialDeflection
#print axioms DeMotu1684.QuadraticInitialDeflection
#check NewtonLimitDynamics.Comparison.constant_force_generated
#print axioms NewtonLimitDynamics.Comparison.constant_force_generated
#check NewtonLimitDynamics.Comparison.generated_sagitta_commute
#print axioms NewtonLimitDynamics.Comparison.generated_sagitta_commute
#check NewtonLimitDynamics.Comparison.symmetric_parabola_sagitta
#print axioms NewtonLimitDynamics.Comparison.symmetric_parabola_sagitta
#check NewtonLimitDynamics.Comparison.twice_positive
#print axioms NewtonLimitDynamics.Comparison.twice_positive
#check NewtonLimitDynamics.Contact.circle_identity_from_perpendicular
#print axioms NewtonLimitDynamics.Contact.circle_identity_from_perpendicular
#check NewtonLimitDynamics.Contact.constant_force_area_coefficients
#print axioms NewtonLimitDynamics.Contact.constant_force_area_coefficients
#check NewtonLimitDynamics.Contact.cubic_rectangle_bound
#print axioms NewtonLimitDynamics.Contact.cubic_rectangle_bound
#check NewtonLimitDynamics.Contact.le_quotient_iff
#print axioms NewtonLimitDynamics.Contact.le_quotient_iff
#check NewtonLimitDynamics.Contact.linear_area_coefficient
#print axioms NewtonLimitDynamics.Contact.linear_area_coefficient
#check NewtonLimitDynamics.Contact.linear_rectangles
#print axioms NewtonLimitDynamics.Contact.linear_rectangles
#check NewtonLimitDynamics.Contact.normal_subtense_bound
#print axioms NewtonLimitDynamics.Contact.normal_subtense_bound
#check NewtonLimitDynamics.Contact.nsum_mul
#print axioms NewtonLimitDynamics.Contact.nsum_mul
#check NewtonLimitDynamics.Contact.parabolic_area_coefficient
#print axioms NewtonLimitDynamics.Contact.parabolic_area_coefficient
#check NewtonLimitDynamics.Contact.quadratic_lower_error
#print axioms NewtonLimitDynamics.Contact.quadratic_lower_error
#check NewtonLimitDynamics.Contact.quadratic_rectangles
#print axioms NewtonLimitDynamics.Contact.quadratic_rectangles
#check NewtonLimitDynamics.Contact.rational_uniform_partition_error
#print axioms NewtonLimitDynamics.Contact.rational_uniform_partition_error
#check NewtonLimitDynamics.Contact.reciprocal_budget_vanishes
#print axioms NewtonLimitDynamics.Contact.reciprocal_budget_vanishes
#check NewtonLimitDynamics.Contact.sum_bound
#print axioms NewtonLimitDynamics.Contact.sum_bound
#check NewtonLimitDynamics.Contact.uniform_partition_error
#print axioms NewtonLimitDynamics.Contact.uniform_partition_error
#check NewtonLimitDynamics.Contact.upper_lower_gap
#print axioms NewtonLimitDynamics.Contact.upper_lower_gap
#check NewtonLimitDynamics.Fraction.add_assoc
#print axioms NewtonLimitDynamics.Fraction.add_assoc
#check NewtonLimitDynamics.Fraction.add_comm
#print axioms NewtonLimitDynamics.Fraction.add_comm
#check NewtonLimitDynamics.Fraction.add_equiv_right
#print axioms NewtonLimitDynamics.Fraction.add_equiv_right
#check NewtonLimitDynamics.Fraction.add_le_add_right
#print axioms NewtonLimitDynamics.Fraction.add_le_add_right
#check NewtonLimitDynamics.Fraction.constructed_triangle_limit
#print axioms NewtonLimitDynamics.Fraction.constructed_triangle_limit
#check NewtonLimitDynamics.Fraction.equiv_iff_mutual_le
#print axioms NewtonLimitDynamics.Fraction.equiv_iff_mutual_le
#check NewtonLimitDynamics.Fraction.equiv_refl
#print axioms NewtonLimitDynamics.Fraction.equiv_refl
#check NewtonLimitDynamics.Fraction.equiv_symm
#print axioms NewtonLimitDynamics.Fraction.equiv_symm
#check NewtonLimitDynamics.Fraction.equiv_trans
#print axioms NewtonLimitDynamics.Fraction.equiv_trans
#check NewtonLimitDynamics.Fraction.half_lt
#print axioms NewtonLimitDynamics.Fraction.half_lt
#check NewtonLimitDynamics.Fraction.mul_add
#print axioms NewtonLimitDynamics.Fraction.mul_add
#check NewtonLimitDynamics.Fraction.mul_assoc
#print axioms NewtonLimitDynamics.Fraction.mul_assoc
#check NewtonLimitDynamics.Fraction.mul_comm
#print axioms NewtonLimitDynamics.Fraction.mul_comm
#check NewtonLimitDynamics.Fraction.mul_equiv_left
#print axioms NewtonLimitDynamics.Fraction.mul_equiv_left
#check NewtonLimitDynamics.Fraction.mul_le_mul_positive
#print axioms NewtonLimitDynamics.Fraction.mul_le_mul_positive
#check NewtonLimitDynamics.Fraction.positive_iff_zero_lt
#print axioms NewtonLimitDynamics.Fraction.positive_iff_zero_lt
#check NewtonLimitDynamics.Fraction.positive_mul
#print axioms NewtonLimitDynamics.Fraction.positive_mul
#check NewtonLimitDynamics.Fraction.square_ratio
#print axioms NewtonLimitDynamics.Fraction.square_ratio
#check NewtonLimitDynamics.Fraction.triangle_area_ratio
#print axioms NewtonLimitDynamics.Fraction.triangle_area_ratio
#check NewtonLimitDynamics.Fraction.triangle_normalized_limit
#print axioms NewtonLimitDynamics.Fraction.triangle_normalized_limit
#check NewtonLimitDynamics.Fraction.ultimate_congr
#print axioms NewtonLimitDynamics.Fraction.ultimate_congr
#check NewtonLimitDynamics.Polygon.InertialControl.drift_small
#print axioms NewtonLimitDynamics.Polygon.InertialControl.drift_small
#check NewtonLimitDynamics.Polygon.InertialControl.endKick_zero_small_increment
#print axioms NewtonLimitDynamics.Polygon.InertialControl.endKick_zero_small_increment
#check NewtonLimitDynamics.Polygon.InertialControl.exists_uniform_inertial_radius
#print axioms NewtonLimitDynamics.Polygon.InertialControl.exists_uniform_inertial_radius
#check NewtonLimitDynamics.Polygon.InertialControl.inertialAt_small_increment
#print axioms NewtonLimitDynamics.Polygon.InertialControl.inertialAt_small_increment
#check NewtonLimitDynamics.Polygon.InertialControl.radius_positive
#print axioms NewtonLimitDynamics.Polygon.InertialControl.radius_positive
#check NewtonLimitDynamics.Polygon.InertialDefect.closedBoundaryTwice_congr
#print axioms NewtonLimitDynamics.Polygon.InertialDefect.closedBoundaryTwice_congr
#check NewtonLimitDynamics.Polygon.InertialDefect.det_congr
#print axioms NewtonLimitDynamics.Polygon.InertialDefect.det_congr
#check NewtonLimitDynamics.Polygon.InertialDefect.inertialEdge_compose
#print axioms NewtonLimitDynamics.Polygon.InertialDefect.inertialEdge_compose
#check NewtonLimitDynamics.Polygon.InertialDefect.inertialEdge_self
#print axioms NewtonLimitDynamics.Polygon.InertialDefect.inertialEdge_self
#check NewtonLimitDynamics.Polygon.InertialDefect.inertialWalk_closed
#print axioms NewtonLimitDynamics.Polygon.InertialDefect.inertialWalk_closed
#check NewtonLimitDynamics.Polygon.InertialDefect.inertialWalk_eq_edge
#print axioms NewtonLimitDynamics.Polygon.InertialDefect.inertialWalk_eq_edge
#check NewtonLimitDynamics.Polygon.InertialDefect.inertial_closedBoundaryTwice
#print axioms NewtonLimitDynamics.Polygon.InertialDefect.inertial_closedBoundaryTwice
#check NewtonLimitDynamics.Polygon.InertialDefect.partitionMotion_closedBoundaryTwice
#print axioms NewtonLimitDynamics.Polygon.InertialDefect.partitionMotion_closedBoundaryTwice
#check NewtonLimitDynamics.Polygon.PartialCell.candidate_partial_residual
#print axioms NewtonLimitDynamics.Polygon.PartialCell.candidate_partial_residual
#check NewtonLimitDynamics.Polygon.PartialCell.endKick_position_kick_free
#print axioms NewtonLimitDynamics.Polygon.PartialCell.endKick_position_kick_free
#check NewtonLimitDynamics.Polygon.PartialCell.partialState_append
#print axioms NewtonLimitDynamics.Polygon.PartialCell.partialState_append
#check NewtonLimitDynamics.Polygon.PartialCell.partialState_position
#print axioms NewtonLimitDynamics.Polygon.PartialCell.partialState_position
#check NewtonLimitDynamics.Polygon.PartialCell.partial_full_cell
#print axioms NewtonLimitDynamics.Polygon.PartialCell.partial_full_cell
#check NewtonLimitDynamics.Polygon.PartialCell.partial_residual_mesh_bound
#print axioms NewtonLimitDynamics.Polygon.PartialCell.partial_residual_mesh_bound
#check NewtonLimitDynamics.Polygon.PartialCell.partial_squares_bound
#print axioms NewtonLimitDynamics.Polygon.PartialCell.partial_squares_bound
#check NewtonLimitDynamics.Polygon.PartialCell.partial_zero
#print axioms NewtonLimitDynamics.Polygon.PartialCell.partial_zero
#check NewtonLimitDynamics.Polygon.PartialCell.partial_zero_force
#print axioms NewtonLimitDynamics.Polygon.PartialCell.partial_zero_force
#check NewtonLimitDynamics.Polygon.PartialCell.squares_append
#print axioms NewtonLimitDynamics.Polygon.PartialCell.squares_append
#check NewtonLimitDynamics.Polygon.PartialCell.stats_append
#print axioms NewtonLimitDynamics.Polygon.PartialCell.stats_append
#check NewtonLimitDynamics.Polygon.PartialCell.total_append
#print axioms NewtonLimitDynamics.Polygon.PartialCell.total_append
#check NewtonLimitDynamics.Polygon.PartitionControl.candidate_partitionMotion_residual
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.candidate_partitionMotion_residual
#check NewtonLimitDynamics.Polygon.PartitionControl.candidate_residual
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.candidate_residual
#check NewtonLimitDynamics.Polygon.PartitionControl.duration_positive
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.duration_positive
#check NewtonLimitDynamics.Polygon.PartitionControl.next_bound
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.next_bound
#check NewtonLimitDynamics.Polygon.PartitionControl.next_identity
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.next_identity
#check NewtonLimitDynamics.Polygon.PartitionControl.partitionMotion_formula
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.partitionMotion_formula
#check NewtonLimitDynamics.Polygon.PartitionControl.residual_mesh_bound
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.residual_mesh_bound
#check NewtonLimitDynamics.Polygon.PartitionControl.residual_nonnegative
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.residual_nonnegative
#check NewtonLimitDynamics.Polygon.PartitionControl.stats_bound
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.stats_bound
#check NewtonLimitDynamics.Polygon.PartitionControl.stats_bound_from
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.stats_bound_from
#check NewtonLimitDynamics.Polygon.PartitionControl.stats_identity
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.stats_identity
#check NewtonLimitDynamics.Polygon.PartitionControl.stats_identity_from
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.stats_identity_from
#check NewtonLimitDynamics.Polygon.TimeSubdivision.example_closedBoundaryTwice
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.example_closedBoundaryTwice
#check NewtonLimitDynamics.Polygon.TimeSubdivision.example_coarse_position
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.example_coarse_position
#check NewtonLimitDynamics.Polygon.TimeSubdivision.example_connector
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.example_connector
#check NewtonLimitDynamics.Polygon.TimeSubdivision.example_endpoints_differ
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.example_endpoints_differ
#check NewtonLimitDynamics.Polygon.TimeSubdivision.example_fine_coarse_endpoints_differ
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.example_fine_coarse_endpoints_differ
#check NewtonLimitDynamics.Polygon.TimeSubdivision.example_fine_middle
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.example_fine_middle
#check NewtonLimitDynamics.Polygon.TimeSubdivision.example_fine_position
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.example_fine_position
#check NewtonLimitDynamics.Polygon.TimeSubdivision.example_half_positive
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.example_half_positive
#check NewtonLimitDynamics.Polygon.TimeSubdivision.example_total_positive
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.example_total_positive
#check NewtonLimitDynamics.Polygon.TimeSubdivision.fine_position_eq_coarse_plus
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.fine_position_eq_coarse_plus
#check NewtonLimitDynamics.Polygon.TimeSubdivision.fine_velocity_eq_coarse
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.fine_velocity_eq_coarse
#check NewtonLimitDynamics.Polygon.TimeSubdivision.totalDuration_positive
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.totalDuration_positive
#check NewtonLimitDynamics.Polygon.ZeroForce.duration_add
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.duration_add
#check NewtonLimitDynamics.Polygon.ZeroForce.endKick_zero
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.endKick_zero
#check NewtonLimitDynamics.Polygon.ZeroForce.inertialAt_add
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.inertialAt_add
#check NewtonLimitDynamics.Polygon.ZeroForce.inertialAt_time_congr
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.inertialAt_time_congr
#check NewtonLimitDynamics.Polygon.ZeroForce.partitionMotion_append
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.partitionMotion_append
#check NewtonLimitDynamics.Polygon.ZeroForce.partitionMotion_cross_partition
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.partitionMotion_cross_partition
#check NewtonLimitDynamics.Polygon.ZeroForce.partitionMotion_cross_partition_state
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.partitionMotion_cross_partition_state
#check NewtonLimitDynamics.Polygon.ZeroForce.partitionMotion_rest
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.partitionMotion_rest
#check NewtonLimitDynamics.Polygon.ZeroForce.partitionMotion_zero_force
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.partitionMotion_zero_force
#check NewtonLimitDynamics.Polygon.ZeroForce.slow_fast_collinear_closedBoundary
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.slow_fast_collinear_closedBoundary
#check NewtonLimitDynamics.Polygon.ZeroForce.slow_fast_different_half_time
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.slow_fast_different_half_time
#check NewtonLimitDynamics.Polygon.ZeroForce.slow_fast_equal_endpoint
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.slow_fast_equal_endpoint
#check NewtonLimitDynamics.Polygon.ZeroForce.slow_two_cell_schedule
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.slow_two_cell_schedule
#check NewtonLimitDynamics.Polygon.ZeroForce.withinCell_position
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.withinCell_position
#check NewtonLimitDynamics.Polygon.ZeroForce.withinCell_position_bounded
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.withinCell_position_bounded
#check NewtonLimitDynamics.Polygon.adjacent_impulseContact_iff
#print axioms NewtonLimitDynamics.Polygon.adjacent_impulseContact_iff
#check NewtonLimitDynamics.Polygon.adjacent_position_contact
#print axioms NewtonLimitDynamics.Polygon.adjacent_position_contact
#check NewtonLimitDynamics.Polygon.adjacent_velocityContact_iff
#print axioms NewtonLimitDynamics.Polygon.adjacent_velocityContact_iff
#check NewtonLimitDynamics.Polygon.all_cell_areas
#print axioms NewtonLimitDynamics.Polygon.all_cell_areas
#check NewtonLimitDynamics.Polygon.central_step_area
#print axioms NewtonLimitDynamics.Polygon.central_step_area
#check NewtonLimitDynamics.Polygon.det_translation
#print axioms NewtonLimitDynamics.Polygon.det_translation
#check NewtonLimitDynamics.Polygon.enclosed_gap_vanishes
#print axioms NewtonLimitDynamics.Polygon.enclosed_gap_vanishes
#check NewtonLimitDynamics.Polygon.equal_swept_area_does_not_identify_next_vertex
#print axioms NewtonLimitDynamics.Polygon.equal_swept_area_does_not_identify_next_vertex
#check NewtonLimitDynamics.Polygon.equal_time_area_reconstruction
#print axioms NewtonLimitDynamics.Polygon.equal_time_area_reconstruction
#check NewtonLimitDynamics.Polygon.extension_identity
#print axioms NewtonLimitDynamics.Polygon.extension_identity
#check NewtonLimitDynamics.Polygon.glue_first
#print axioms NewtonLimitDynamics.Polygon.glue_first
#check NewtonLimitDynamics.Polygon.glue_last
#print axioms NewtonLimitDynamics.Polygon.glue_last
#check NewtonLimitDynamics.Polygon.glue_middle_from_left
#print axioms NewtonLimitDynamics.Polygon.glue_middle_from_left
#check NewtonLimitDynamics.Polygon.glue_middle_from_right
#print axioms NewtonLimitDynamics.Polygon.glue_middle_from_right
#check NewtonLimitDynamics.Polygon.glued_position_contact
#print axioms NewtonLimitDynamics.Polygon.glued_position_contact
#check NewtonLimitDynamics.Polygon.impulseContact_position
#print axioms NewtonLimitDynamics.Polygon.impulseContact_position
#check NewtonLimitDynamics.Polygon.inward_impulses_distinct_next_vertex
#print axioms NewtonLimitDynamics.Polygon.inward_impulses_distinct_next_vertex
#check NewtonLimitDynamics.Polygon.inward_impulses_same_swept
#print axioms NewtonLimitDynamics.Polygon.inward_impulses_same_swept
#check NewtonLimitDynamics.Polygon.inward_oneCell_refinement_compatible
#print axioms NewtonLimitDynamics.Polygon.inward_oneCell_refinement_compatible
#check NewtonLimitDynamics.Polygon.inward_oneCell_refinement_defect
#print axioms NewtonLimitDynamics.Polygon.inward_oneCell_refinement_defect
#check NewtonLimitDynamics.Polygon.isum_mono
#print axioms NewtonLimitDynamics.Polygon.isum_mono
#check NewtonLimitDynamics.Polygon.isum_mul
#print axioms NewtonLimitDynamics.Polygon.isum_mul
#check NewtonLimitDynamics.Polygon.latticeMotionCell_adjacent_position_contact
#print axioms NewtonLimitDynamics.Polygon.latticeMotionCell_adjacent_position_contact
#check NewtonLimitDynamics.Polygon.latticeMotionCell_impulseContact
#print axioms NewtonLimitDynamics.Polygon.latticeMotionCell_impulseContact
#check NewtonLimitDynamics.Polygon.latticeMotionCell_zero_impulse_velocityContact
#print axioms NewtonLimitDynamics.Polygon.latticeMotionCell_zero_impulse_velocityContact
#check NewtonLimitDynamics.Polygon.lattice_step_velocity_jump
#print axioms NewtonLimitDynamics.Polygon.lattice_step_velocity_jump
#check NewtonLimitDynamics.Polygon.motion_adjacent_pair_position_contact
#print axioms NewtonLimitDynamics.Polygon.motion_adjacent_pair_position_contact
#check NewtonLimitDynamics.Polygon.motion_lattice_velocity_jump
#print axioms NewtonLimitDynamics.Polygon.motion_lattice_velocity_jump
#check NewtonLimitDynamics.Polygon.motion_restart
#print axioms NewtonLimitDynamics.Polygon.motion_restart
#check NewtonLimitDynamics.Polygon.oneCellMotionRefinementCompatible_end
#print axioms NewtonLimitDynamics.Polygon.oneCellMotionRefinementCompatible_end
#check NewtonLimitDynamics.Polygon.oneCellMotionRefinementCompatible_start
#print axioms NewtonLimitDynamics.Polygon.oneCellMotionRefinementCompatible_start
#check NewtonLimitDynamics.Polygon.parallel_identity
#print axioms NewtonLimitDynamics.Polygon.parallel_identity
#check NewtonLimitDynamics.Polygon.rectangle_gap_bound
#print axioms NewtonLimitDynamics.Polygon.rectangle_gap_bound
#check NewtonLimitDynamics.Polygon.refinementDefect_eq_zero_iff
#print axioms NewtonLimitDynamics.Polygon.refinementDefect_eq_zero_iff
#check NewtonLimitDynamics.Polygon.refinementStripTwice_eq_triangle
#print axioms NewtonLimitDynamics.Polygon.refinementStripTwice_eq_triangle
#check NewtonLimitDynamics.Polygon.refinementStripTwice_translation
#print axioms NewtonLimitDynamics.Polygon.refinementStripTwice_translation
#check NewtonLimitDynamics.Polygon.restriction_cell
#print axioms NewtonLimitDynamics.Polygon.restriction_cell
#check NewtonLimitDynamics.Polygon.sector_ratio_reconstruction
#print axioms NewtonLimitDynamics.Polygon.sector_ratio_reconstruction
#check NewtonLimitDynamics.Polygon.sum_constant
#print axioms NewtonLimitDynamics.Polygon.sum_constant
#check NewtonLimitDynamics.Polygon.swept_eq
#print axioms NewtonLimitDynamics.Polygon.swept_eq
#check NewtonLimitDynamics.Polygon.telescoping
#print axioms NewtonLimitDynamics.Polygon.telescoping
#check NewtonLimitDynamics.Polygon.velocityContact_position
#print axioms NewtonLimitDynamics.Polygon.velocityContact_position
#check NewtonLimitDynamics.enclosure_reconstruction
#print axioms NewtonLimitDynamics.enclosure_reconstruction
#check NewtonLimitDynamics.near_and
#print axioms NewtonLimitDynamics.near_and
#check NewtonLimitDynamics.near_has_witness
#print axioms NewtonLimitDynamics.near_has_witness
#check NewtonLimitDynamics.not_near_false
#print axioms NewtonLimitDynamics.not_near_false
#check Principia1687.constructed_quadratic_bridge
#print axioms Principia1687.constructed_quadratic_bridge
#check Principia1687.discharges_quadraticPremise_reconstruction
#print axioms Principia1687.discharges_quadraticPremise_reconstruction
#check Principia1687.lemmaX_reconstruction
#print axioms Principia1687.lemmaX_reconstruction
#check Principia1713.corollary4_coefficient_reconstruction
#print axioms Principia1713.corollary4_coefficient_reconstruction
#check Principia1713.corollary5_coefficient_reconstruction
#print axioms Principia1713.corollary5_coefficient_reconstruction
#check Principia1713.lemmaX_reconstruction
#print axioms Principia1713.lemmaX_reconstruction
