import NewtonLimitDynamics

-- Generated; compile with lake env lean research/CheckReferences.lean.
#check DeMotu1684.AreaLaw.natp00089_finite_block_comparison
#print axioms DeMotu1684.AreaLaw.natp00089_finite_block_comparison
#check DeMotu1684.AreaLaw.natp00089_finite_equal_areas
#print axioms DeMotu1684.AreaLaw.natp00089_finite_equal_areas
#check DeMotu1684.AreaLaw.natp00089_polygon_trajectory_defect_control
#print axioms DeMotu1684.AreaLaw.natp00089_polygon_trajectory_defect_control
#check DeMotu1684.AreaLaw.natp00090_finite_block_comparison
#print axioms DeMotu1684.AreaLaw.natp00090_finite_block_comparison
#check DeMotu1684.AreaLaw.natp00090_finite_equal_areas
#print axioms DeMotu1684.AreaLaw.natp00090_finite_equal_areas
#check DeMotu1684.AreaLaw.natp00090_polygon_trajectory_defect_control
#print axioms DeMotu1684.AreaLaw.natp00090_polygon_trajectory_defect_control
#check DeMotu1684.QuadraticInitialDeflection
#print axioms DeMotu1684.QuadraticInitialDeflection
#check NewtonLimitDynamics.Comparison.CircleCompare.force_ratio_is_sagitta_ratio
#print axioms NewtonLimitDynamics.Comparison.CircleCompare.force_ratio_is_sagitta_ratio
#check NewtonLimitDynamics.Comparison.constant_force_generated
#print axioms NewtonLimitDynamics.Comparison.constant_force_generated
#check NewtonLimitDynamics.Comparison.generated_sagitta_commute
#print axioms NewtonLimitDynamics.Comparison.generated_sagitta_commute
#check NewtonLimitDynamics.Comparison.symmetric_parabola_sagitta
#print axioms NewtonLimitDynamics.Comparison.symmetric_parabola_sagitta
#check NewtonLimitDynamics.Comparison.twice_positive
#print axioms NewtonLimitDynamics.Comparison.twice_positive
#check NewtonLimitDynamics.Contact.circle_identity_from_perpendicular
#print axioms NewtonLimitDynamics.Contact.circle_identity_from_perpendicular
#check NewtonLimitDynamics.Contact.constant_force_area_coefficients
#print axioms NewtonLimitDynamics.Contact.constant_force_area_coefficients
#check NewtonLimitDynamics.Contact.cubic_rectangle_bound
#print axioms NewtonLimitDynamics.Contact.cubic_rectangle_bound
#check NewtonLimitDynamics.Contact.le_quotient_iff
#print axioms NewtonLimitDynamics.Contact.le_quotient_iff
#check NewtonLimitDynamics.Contact.linear_area_coefficient
#print axioms NewtonLimitDynamics.Contact.linear_area_coefficient
#check NewtonLimitDynamics.Contact.linear_rectangles
#print axioms NewtonLimitDynamics.Contact.linear_rectangles
#check NewtonLimitDynamics.Contact.normal_subtense_bound
#print axioms NewtonLimitDynamics.Contact.normal_subtense_bound
#check NewtonLimitDynamics.Contact.nsum_mul
#print axioms NewtonLimitDynamics.Contact.nsum_mul
#check NewtonLimitDynamics.Contact.parabolic_area_coefficient
#print axioms NewtonLimitDynamics.Contact.parabolic_area_coefficient
#check NewtonLimitDynamics.Contact.quadratic_lower_error
#print axioms NewtonLimitDynamics.Contact.quadratic_lower_error
#check NewtonLimitDynamics.Contact.quadratic_rectangles
#print axioms NewtonLimitDynamics.Contact.quadratic_rectangles
#check NewtonLimitDynamics.Contact.rational_uniform_partition_error
#print axioms NewtonLimitDynamics.Contact.rational_uniform_partition_error
#check NewtonLimitDynamics.Contact.reciprocal_budget_vanishes
#print axioms NewtonLimitDynamics.Contact.reciprocal_budget_vanishes
#check NewtonLimitDynamics.Contact.sum_bound
#print axioms NewtonLimitDynamics.Contact.sum_bound
#check NewtonLimitDynamics.Contact.uniform_partition_error
#print axioms NewtonLimitDynamics.Contact.uniform_partition_error
#check NewtonLimitDynamics.Contact.upper_lower_gap
#print axioms NewtonLimitDynamics.Contact.upper_lower_gap
#check NewtonLimitDynamics.Diagnostic.InverseCubeAreal.equalAreal_inverseCube
#print axioms NewtonLimitDynamics.Diagnostic.InverseCubeAreal.equalAreal_inverseCube
#check NewtonLimitDynamics.Diagnostic.InverseCubeAreal.inverseCube_equalAreal
#print axioms NewtonLimitDynamics.Diagnostic.InverseCubeAreal.inverseCube_equalAreal
#check NewtonLimitDynamics.Diagnostic.InverseCubeAreal.inverseSquare_areal_varies
#print axioms NewtonLimitDynamics.Diagnostic.InverseCubeAreal.inverseSquare_areal_varies
#check NewtonLimitDynamics.Diagnostic.PhaseArea.cell_area2
#print axioms NewtonLimitDynamics.Diagnostic.PhaseArea.cell_area2
#check NewtonLimitDynamics.Diagnostic.PhaseArea.cell_energyD
#print axioms NewtonLimitDynamics.Diagnostic.PhaseArea.cell_energyD
#check NewtonLimitDynamics.Diagnostic.PhaseArea.cells_area2
#print axioms NewtonLimitDynamics.Diagnostic.PhaseArea.cells_area2
#check NewtonLimitDynamics.Diagnostic.PhaseArea.drift_area2
#print axioms NewtonLimitDynamics.Diagnostic.PhaseArea.drift_area2
#check NewtonLimitDynamics.Diagnostic.PhaseArea.drift_rigid
#print axioms NewtonLimitDynamics.Diagnostic.PhaseArea.drift_rigid
#check NewtonLimitDynamics.Diagnostic.PhaseArea.energyD_depends_on_mesh
#print axioms NewtonLimitDynamics.Diagnostic.PhaseArea.energyD_depends_on_mesh
#check NewtonLimitDynamics.Diagnostic.PhaseArea.kick_area2
#print axioms NewtonLimitDynamics.Diagnostic.PhaseArea.kick_area2
#check NewtonLimitDynamics.Diagnostic.PhaseArea.kick_rigid
#print axioms NewtonLimitDynamics.Diagnostic.PhaseArea.kick_rigid
#check NewtonLimitDynamics.Diagnostic.PhaseArea.refinement_moves_points_keeps_area
#print axioms NewtonLimitDynamics.Diagnostic.PhaseArea.refinement_moves_points_keeps_area
#check NewtonLimitDynamics.FiniteGrowth.amplification_append
#print axioms NewtonLimitDynamics.FiniteGrowth.amplification_append
#check NewtonLimitDynamics.FiniteGrowth.amplification_cons
#print axioms NewtonLimitDynamics.FiniteGrowth.amplification_cons
#check NewtonLimitDynamics.FiniteGrowth.amplification_empty
#print axioms NewtonLimitDynamics.FiniteGrowth.amplification_empty
#check NewtonLimitDynamics.FiniteGrowth.amplification_nonnegative
#print axioms NewtonLimitDynamics.FiniteGrowth.amplification_nonnegative
#check NewtonLimitDynamics.FiniteGrowth.boundary_sample
#print axioms NewtonLimitDynamics.FiniteGrowth.boundary_sample
#check NewtonLimitDynamics.FiniteGrowth.cofactor_bound
#print axioms NewtonLimitDynamics.FiniteGrowth.cofactor_bound
#check NewtonLimitDynamics.FiniteGrowth.cofactor_step
#print axioms NewtonLimitDynamics.FiniteGrowth.cofactor_step
#check NewtonLimitDynamics.FiniteGrowth.factorProduct_append
#print axioms NewtonLimitDynamics.FiniteGrowth.factorProduct_append
#check NewtonLimitDynamics.FiniteGrowth.factorProduct_nonnegative
#print axioms NewtonLimitDynamics.FiniteGrowth.factorProduct_nonnegative
#check NewtonLimitDynamics.FiniteGrowth.factorProduct_replicate
#print axioms NewtonLimitDynamics.FiniteGrowth.factorProduct_replicate
#check NewtonLimitDynamics.FiniteGrowth.factor_eq_one_add
#print axioms NewtonLimitDynamics.FiniteGrowth.factor_eq_one_add
#check NewtonLimitDynamics.FiniteGrowth.missing_smallness_counterexample
#print axioms NewtonLimitDynamics.FiniteGrowth.missing_smallness_counterexample
#check NewtonLimitDynamics.FiniteGrowth.uniform_amplification
#print axioms NewtonLimitDynamics.FiniteGrowth.uniform_amplification
#check NewtonLimitDynamics.FiniteGrowth.uniform_product_bound
#print axioms NewtonLimitDynamics.FiniteGrowth.uniform_product_bound
#check NewtonLimitDynamics.FiniteGrowth.weightSum_append
#print axioms NewtonLimitDynamics.FiniteGrowth.weightSum_append
#check NewtonLimitDynamics.FiniteGrowth.weightSum_nonnegative
#print axioms NewtonLimitDynamics.FiniteGrowth.weightSum_nonnegative
#check NewtonLimitDynamics.FiniteGrowth.weightSum_replicate
#print axioms NewtonLimitDynamics.FiniteGrowth.weightSum_replicate
#check NewtonLimitDynamics.FiniteGrowth.zero_increments
#print axioms NewtonLimitDynamics.FiniteGrowth.zero_increments
#check NewtonLimitDynamics.Fraction.abs_add_le
#print axioms NewtonLimitDynamics.Fraction.abs_add_le
#check NewtonLimitDynamics.Fraction.abs_add_strict_example
#print axioms NewtonLimitDynamics.Fraction.abs_add_strict_example
#check NewtonLimitDynamics.Fraction.abs_equiv
#print axioms NewtonLimitDynamics.Fraction.abs_equiv
#check NewtonLimitDynamics.Fraction.abs_mul
#print axioms NewtonLimitDynamics.Fraction.abs_mul
#check NewtonLimitDynamics.Fraction.abs_neg
#print axioms NewtonLimitDynamics.Fraction.abs_neg
#check NewtonLimitDynamics.Fraction.abs_num_nonnegative
#print axioms NewtonLimitDynamics.Fraction.abs_num_nonnegative
#check NewtonLimitDynamics.Fraction.abs_of_nonnegative
#print axioms NewtonLimitDynamics.Fraction.abs_of_nonnegative
#check NewtonLimitDynamics.Fraction.add_assoc
#print axioms NewtonLimitDynamics.Fraction.add_assoc
#check NewtonLimitDynamics.Fraction.add_comm
#print axioms NewtonLimitDynamics.Fraction.add_comm
#check NewtonLimitDynamics.Fraction.add_equiv
#print axioms NewtonLimitDynamics.Fraction.add_equiv
#check NewtonLimitDynamics.Fraction.add_equiv_left
#print axioms NewtonLimitDynamics.Fraction.add_equiv_left
#check NewtonLimitDynamics.Fraction.add_equiv_right
#print axioms NewtonLimitDynamics.Fraction.add_equiv_right
#check NewtonLimitDynamics.Fraction.add_le_add
#print axioms NewtonLimitDynamics.Fraction.add_le_add
#check NewtonLimitDynamics.Fraction.add_le_add_left
#print axioms NewtonLimitDynamics.Fraction.add_le_add_left
#check NewtonLimitDynamics.Fraction.add_le_add_right
#print axioms NewtonLimitDynamics.Fraction.add_le_add_right
#check NewtonLimitDynamics.Fraction.add_mul
#print axioms NewtonLimitDynamics.Fraction.add_mul
#check NewtonLimitDynamics.Fraction.add_zero
#print axioms NewtonLimitDynamics.Fraction.add_zero
#check NewtonLimitDynamics.Fraction.constructed_triangle_limit
#print axioms NewtonLimitDynamics.Fraction.constructed_triangle_limit
#check NewtonLimitDynamics.Fraction.equiv_iff_mutual_le
#print axioms NewtonLimitDynamics.Fraction.equiv_iff_mutual_le
#check NewtonLimitDynamics.Fraction.equiv_refl
#print axioms NewtonLimitDynamics.Fraction.equiv_refl
#check NewtonLimitDynamics.Fraction.equiv_symm
#print axioms NewtonLimitDynamics.Fraction.equiv_symm
#check NewtonLimitDynamics.Fraction.equiv_trans
#print axioms NewtonLimitDynamics.Fraction.equiv_trans
#check NewtonLimitDynamics.Fraction.half_lt
#print axioms NewtonLimitDynamics.Fraction.half_lt
#check NewtonLimitDynamics.Fraction.le_add_nonnegative
#print axioms NewtonLimitDynamics.Fraction.le_add_nonnegative
#check NewtonLimitDynamics.Fraction.le_equiv_left
#print axioms NewtonLimitDynamics.Fraction.le_equiv_left
#check NewtonLimitDynamics.Fraction.le_equiv_right
#print axioms NewtonLimitDynamics.Fraction.le_equiv_right
#check NewtonLimitDynamics.Fraction.le_of_equiv
#print axioms NewtonLimitDynamics.Fraction.le_of_equiv
#check NewtonLimitDynamics.Fraction.mul_add
#print axioms NewtonLimitDynamics.Fraction.mul_add
#check NewtonLimitDynamics.Fraction.mul_assoc
#print axioms NewtonLimitDynamics.Fraction.mul_assoc
#check NewtonLimitDynamics.Fraction.mul_comm
#print axioms NewtonLimitDynamics.Fraction.mul_comm
#check NewtonLimitDynamics.Fraction.mul_equiv
#print axioms NewtonLimitDynamics.Fraction.mul_equiv
#check NewtonLimitDynamics.Fraction.mul_equiv_left
#print axioms NewtonLimitDynamics.Fraction.mul_equiv_left
#check NewtonLimitDynamics.Fraction.mul_equiv_right
#print axioms NewtonLimitDynamics.Fraction.mul_equiv_right
#check NewtonLimitDynamics.Fraction.mul_le_mul_nonnegative
#print axioms NewtonLimitDynamics.Fraction.mul_le_mul_nonnegative
#check NewtonLimitDynamics.Fraction.mul_le_mul_nonnegative_left
#print axioms NewtonLimitDynamics.Fraction.mul_le_mul_nonnegative_left
#check NewtonLimitDynamics.Fraction.mul_le_mul_positive
#print axioms NewtonLimitDynamics.Fraction.mul_le_mul_positive
#check NewtonLimitDynamics.Fraction.mul_zero
#print axioms NewtonLimitDynamics.Fraction.mul_zero
#check NewtonLimitDynamics.Fraction.nonnegative_add
#print axioms NewtonLimitDynamics.Fraction.nonnegative_add
#check NewtonLimitDynamics.Fraction.nonnegative_mul
#print axioms NewtonLimitDynamics.Fraction.nonnegative_mul
#check NewtonLimitDynamics.Fraction.positive_iff_zero_lt
#print axioms NewtonLimitDynamics.Fraction.positive_iff_zero_lt
#check NewtonLimitDynamics.Fraction.positive_mul
#print axioms NewtonLimitDynamics.Fraction.positive_mul
#check NewtonLimitDynamics.Fraction.square_ratio
#print axioms NewtonLimitDynamics.Fraction.square_ratio
#check NewtonLimitDynamics.Fraction.triangle_area_ratio
#print axioms NewtonLimitDynamics.Fraction.triangle_area_ratio
#check NewtonLimitDynamics.Fraction.triangle_normalized_limit
#print axioms NewtonLimitDynamics.Fraction.triangle_normalized_limit
#check NewtonLimitDynamics.Fraction.ultimate_congr
#print axioms NewtonLimitDynamics.Fraction.ultimate_congr
#check NewtonLimitDynamics.Polygon.BinaryTime.addressEquiv_refl
#print axioms NewtonLimitDynamics.Polygon.BinaryTime.addressEquiv_refl
#check NewtonLimitDynamics.Polygon.BinaryTime.addressEquiv_symm
#print axioms NewtonLimitDynamics.Polygon.BinaryTime.addressEquiv_symm
#check NewtonLimitDynamics.Polygon.BinaryTime.addressEquiv_trans
#print axioms NewtonLimitDynamics.Polygon.BinaryTime.addressEquiv_trans
#check NewtonLimitDynamics.Polygon.BinaryTime.adjacent_time_bound
#print axioms NewtonLimitDynamics.Polygon.BinaryTime.adjacent_time_bound
#check NewtonLimitDynamics.Polygon.BinaryTime.doubleTail_lt_tolerance
#print axioms NewtonLimitDynamics.Polygon.BinaryTime.doubleTail_lt_tolerance
#check NewtonLimitDynamics.Polygon.BinaryTime.finite_gap_time
#print axioms NewtonLimitDynamics.Polygon.BinaryTime.finite_gap_time
#check NewtonLimitDynamics.Polygon.BinaryTime.scalarState_distance
#print axioms NewtonLimitDynamics.Polygon.BinaryTime.scalarState_distance
#check NewtonLimitDynamics.Polygon.BinaryTime.tail_double
#print axioms NewtonLimitDynamics.Polygon.BinaryTime.tail_double
#check NewtonLimitDynamics.Polygon.BinaryTime.timeState_distance
#print axioms NewtonLimitDynamics.Polygon.BinaryTime.timeState_distance
#check NewtonLimitDynamics.Polygon.BinaryTime.time_cauchy
#print axioms NewtonLimitDynamics.Polygon.BinaryTime.time_cauchy
#check NewtonLimitDynamics.Polygon.BinaryTime.time_step_difference
#print axioms NewtonLimitDynamics.Polygon.BinaryTime.time_step_difference
#check NewtonLimitDynamics.Polygon.BinaryTime.two_sided_time
#print axioms NewtonLimitDynamics.Polygon.BinaryTime.two_sided_time
#check NewtonLimitDynamics.Polygon.CauchyValues.add_lt_add_left
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.add_lt_add_left
#check NewtonLimitDynamics.Polygon.CauchyValues.binaryValue_prefix_bound
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.binaryValue_prefix_bound
#check NewtonLimitDynamics.Polygon.CauchyValues.constantName_equiv_iff
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.constantName_equiv_iff
#check NewtonLimitDynamics.Polygon.CauchyValues.constant_approximants_converge
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.constant_approximants_converge
#check NewtonLimitDynamics.Polygon.CauchyValues.distance_self_lt
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.distance_self_lt
#check NewtonLimitDynamics.Polygon.CauchyValues.distance_zero_iff_stateEquiv
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.distance_zero_iff_stateEquiv
#check NewtonLimitDynamics.Polygon.CauchyValues.embed_eq_iff_stateEquiv
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.embed_eq_iff_stateEquiv
#check NewtonLimitDynamics.Polygon.CauchyValues.le_add_cancel_left
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.le_add_cancel_left
#check NewtonLimitDynamics.Polygon.CauchyValues.lt_equiv_right
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.lt_equiv_right
#check NewtonLimitDynamics.Polygon.CauchyValues.nameBound_congr
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.nameBound_congr
#check NewtonLimitDynamics.Polygon.CauchyValues.nameBound_of_eventual_le
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.nameBound_of_eventual_le
#check NewtonLimitDynamics.Polygon.CauchyValues.nameBound_symm
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.nameBound_symm
#check NewtonLimitDynamics.Polygon.CauchyValues.nameBound_triangle
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.nameBound_triangle
#check NewtonLimitDynamics.Polygon.CauchyValues.nameBound_zero_iff
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.nameBound_zero_iff
#check NewtonLimitDynamics.Polygon.CauchyValues.nameEquiv_refl
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.nameEquiv_refl
#check NewtonLimitDynamics.Polygon.CauchyValues.nameEquiv_symm
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.nameEquiv_symm
#check NewtonLimitDynamics.Polygon.CauchyValues.nameEquiv_trans
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.nameEquiv_trans
#check NewtonLimitDynamics.Polygon.CauchyValues.rational_time_uniform_value_bound
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.rational_time_uniform_value_bound
#check NewtonLimitDynamics.Polygon.CauchyValues.sample_endpoint_value_ne_initial
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.sample_endpoint_value_ne_initial
#check NewtonLimitDynamics.Polygon.CauchyValues.sample_endpoint_zero_distance
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.sample_endpoint_zero_distance
#check NewtonLimitDynamics.Polygon.CauchyValues.sample_lower_all_levels
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.sample_lower_all_levels
#check NewtonLimitDynamics.Polygon.CauchyValues.sample_tail_zero
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.sample_tail_zero
#check NewtonLimitDynamics.Polygon.CauchyValues.timeValue_bound
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.timeValue_bound
#check NewtonLimitDynamics.Polygon.CauchyValues.within_realize
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.within_realize
#check NewtonLimitDynamics.Polygon.CauchyValues.within_symm
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.within_symm
#check NewtonLimitDynamics.Polygon.CauchyValues.within_triangle
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.within_triangle
#check NewtonLimitDynamics.Polygon.CauchyValues.within_zero_iff
#print axioms NewtonLimitDynamics.Polygon.CauchyValues.within_zero_iff
#check NewtonLimitDynamics.Polygon.CentralSchedule.cell_momentum
#print axioms NewtonLimitDynamics.Polygon.CentralSchedule.cell_momentum
#check NewtonLimitDynamics.Polygon.CentralSchedule.central_kick
#print axioms NewtonLimitDynamics.Polygon.CentralSchedule.central_kick
#check NewtonLimitDynamics.Polygon.CentralSchedule.det_cell_area
#print axioms NewtonLimitDynamics.Polygon.CentralSchedule.det_cell_area
#check NewtonLimitDynamics.Polygon.CentralSchedule.det_drift
#print axioms NewtonLimitDynamics.Polygon.CentralSchedule.det_drift
#check NewtonLimitDynamics.Polygon.CentralSchedule.det_kick_split
#print axioms NewtonLimitDynamics.Polygon.CentralSchedule.det_kick_split
#check NewtonLimitDynamics.Polygon.CentralSchedule.harmonic_central
#print axioms NewtonLimitDynamics.Polygon.CentralSchedule.harmonic_central
#check NewtonLimitDynamics.Polygon.CentralSchedule.harmonic_equal_swept
#print axioms NewtonLimitDynamics.Polygon.CentralSchedule.harmonic_equal_swept
#check NewtonLimitDynamics.Polygon.CentralSchedule.harmonic_refinement_changes_velocity
#print axioms NewtonLimitDynamics.Polygon.CentralSchedule.harmonic_refinement_changes_velocity
#check NewtonLimitDynamics.Polygon.CentralSchedule.refine_position
#print axioms NewtonLimitDynamics.Polygon.CentralSchedule.refine_position
#check NewtonLimitDynamics.Polygon.CentralSchedule.refine_velocity
#print axioms NewtonLimitDynamics.Polygon.CentralSchedule.refine_velocity
#check NewtonLimitDynamics.Polygon.CentralSchedule.schedule_momentum
#print axioms NewtonLimitDynamics.Polygon.CentralSchedule.schedule_momentum
#check NewtonLimitDynamics.Polygon.CentralSchedule.swept_eq
#print axioms NewtonLimitDynamics.Polygon.CentralSchedule.swept_eq
#check NewtonLimitDynamics.Polygon.CentralSchedule.unequal_cells_converse
#print axioms NewtonLimitDynamics.Polygon.CentralSchedule.unequal_cells_converse
#check NewtonLimitDynamics.Polygon.Converse.det_deflection
#print axioms NewtonLimitDynamics.Polygon.Converse.det_deflection
#check NewtonLimitDynamics.Polygon.Converse.det_sub
#print axioms NewtonLimitDynamics.Polygon.Converse.det_sub
#check NewtonLimitDynamics.Polygon.Converse.equal_area_central_step
#print axioms NewtonLimitDynamics.Polygon.Converse.equal_area_central_step
#check NewtonLimitDynamics.Polygon.Converse.equal_area_parallel
#print axioms NewtonLimitDynamics.Polygon.Converse.equal_area_parallel
#check NewtonLimitDynamics.Polygon.Converse.equal_areas_all_central
#print axioms NewtonLimitDynamics.Polygon.Converse.equal_areas_all_central
#check NewtonLimitDynamics.Polygon.Converse.extend_relative
#print axioms NewtonLimitDynamics.Polygon.Converse.extend_relative
#check NewtonLimitDynamics.Polygon.Converse.moving_centre_equal_areas_central
#print axioms NewtonLimitDynamics.Polygon.Converse.moving_centre_equal_areas_central
#check NewtonLimitDynamics.Polygon.Converse.outward_kick_equal_area
#print axioms NewtonLimitDynamics.Polygon.Converse.outward_kick_equal_area
#check NewtonLimitDynamics.Polygon.Converse.parallel_equal_area
#print axioms NewtonLimitDynamics.Polygon.Converse.parallel_equal_area
#check NewtonLimitDynamics.Polygon.Converse.parallel_is_multiple
#print axioms NewtonLimitDynamics.Polygon.Converse.parallel_is_multiple
#check NewtonLimitDynamics.Polygon.Converse.unsigned_equal_area_not_central
#print axioms NewtonLimitDynamics.Polygon.Converse.unsigned_equal_area_not_central
#check NewtonLimitDynamics.Polygon.Converse.vertex_at_centre_degenerate
#print axioms NewtonLimitDynamics.Polygon.Converse.vertex_at_centre_degenerate
#check NewtonLimitDynamics.Polygon.ConvexCover.ball_inside_square
#print axioms NewtonLimitDynamics.Polygon.ConvexCover.ball_inside_square
#check NewtonLimitDynamics.Polygon.ConvexCover.complement_abs
#print axioms NewtonLimitDynamics.Polygon.ConvexCover.complement_abs
#check NewtonLimitDynamics.Polygon.ConvexCover.complement_nonnegative
#print axioms NewtonLimitDynamics.Polygon.ConvexCover.complement_nonnegative
#check NewtonLimitDynamics.Polygon.ConvexCover.drift_offset
#print axioms NewtonLimitDynamics.Polygon.ConvexCover.drift_offset
#check NewtonLimitDynamics.Polygon.ConvexCover.interval_abs
#print axioms NewtonLimitDynamics.Polygon.ConvexCover.interval_abs
#check NewtonLimitDynamics.Polygon.ConvexCover.lerp_ball_bound
#print axioms NewtonLimitDynamics.Polygon.ConvexCover.lerp_ball_bound
#check NewtonLimitDynamics.Polygon.ConvexCover.lerp_offset
#print axioms NewtonLimitDynamics.Polygon.ConvexCover.lerp_offset
#check NewtonLimitDynamics.Polygon.ConvexCover.matchedPatch_ball
#print axioms NewtonLimitDynamics.Polygon.ConvexCover.matchedPatch_ball
#check NewtonLimitDynamics.Polygon.ConvexCover.matchedPatch_square
#print axioms NewtonLimitDynamics.Polygon.ConvexCover.matchedPatch_square
#check NewtonLimitDynamics.Polygon.ConvexCover.pointSub_chain
#print axioms NewtonLimitDynamics.Polygon.ConvexCover.pointSub_chain
#check NewtonLimitDynamics.Polygon.ConvexCover.pointSub_self_zero
#print axioms NewtonLimitDynamics.Polygon.ConvexCover.pointSub_self_zero
#check NewtonLimitDynamics.Polygon.ConvexCover.pointSub_triangle
#print axioms NewtonLimitDynamics.Polygon.ConvexCover.pointSub_triangle
#check NewtonLimitDynamics.Polygon.ConvexCover.weights_sum_one
#print axioms NewtonLimitDynamics.Polygon.ConvexCover.weights_sum_one
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.actual_error_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.actual_error_bound
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.coarseAt_schedule
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.coarseAt_schedule
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.coarse_norm_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.coarse_norm_bound
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.errorBudget_nonnegative
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.errorBudget_nonnegative
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.fineAt_schedule
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.fineAt_schedule
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.fineFactor_nonnegative
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.fineFactor_nonnegative
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.fine_perturbation
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.fine_perturbation
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.fpower_nonnegative
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.fpower_nonnegative
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.kappa_nonnegative
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.kappa_nonnegative
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.localFactor_nonnegative
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.localFactor_nonnegative
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.local_error_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.local_error_bound
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.local_error_expanded_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.local_error_expanded_bound
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.local_error_identity
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.local_error_identity
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.sample_initial_error
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.sample_initial_error
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.sample_local_factor
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.sample_local_factor
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.sample_one_block_budget
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.sample_one_block_budget
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.sample_one_block_distinct
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.sample_one_block_distinct
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.sample_one_block_error
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.sample_one_block_error
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.sample_two_block_error
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.sample_two_block_error
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.sample_zero_blocks
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.sample_zero_blocks
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.sample_zero_budget
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.sample_zero_budget
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.sample_zero_error
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.sample_zero_error
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.schedules_common_time
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.schedules_common_time
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.stateSub_self_norm_zero
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.stateSub_self_norm_zero
#check NewtonLimitDynamics.Polygon.HarmonicAccumulation.stateSub_triangle
#print axioms NewtonLimitDynamics.Polygon.HarmonicAccumulation.stateSub_triangle
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.adjacentCap_tail
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.adjacentCap_tail
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.adjacent_error_le
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.adjacent_error_le
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.adjacent_error_le_add
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.adjacent_error_le_add
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.all_zero_prefix
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.all_zero_prefix
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.all_zero_ticks
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.all_zero_ticks
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.bit_le_one
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.bit_le_one
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.cell_increment_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.cell_increment_bound
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.cell_parameter_bound_one
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.cell_parameter_bound_one
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.coefficient_nonnegative
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.coefficient_nonnegative
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.doubleTail_lt_tolerance
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.doubleTail_lt_tolerance
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.elapsed_replicate
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.elapsed_replicate
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.fine_optional_increment
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.fine_optional_increment
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.fine_prefix_state_le_two
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.fine_prefix_state_le_two
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.finite_gap_error
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.finite_gap_error
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.prefix_cauchy
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.prefix_cauchy
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.prefix_coarse
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.prefix_coarse
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.prefix_elapsed
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.prefix_elapsed
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.prefix_elapsed_le_time
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.prefix_elapsed_le_time
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.prefix_next
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.prefix_next
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.prefix_refinement_error
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.prefix_refinement_error
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.prefix_state_le_two
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.prefix_state_le_two
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.prefix_totalTime_le
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.prefix_totalTime_le
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.sample_coefficient
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.sample_coefficient
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.sample_first_error
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.sample_first_error
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.sample_second_error
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.sample_second_error
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.sample_ticks
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.sample_ticks
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.schedule_replicate_step
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.schedule_replicate_step
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.tail_double
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.tail_double
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.tail_halving
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.tail_halving
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.ticks_le_blocks
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.ticks_le_blocks
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.ticks_lt_blocks
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.ticks_lt_blocks
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.ticks_next
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.ticks_next
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.two_sided_error
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.two_sided_error
#check NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.zero_time_prefix
#print axioms NewtonLimitDynamics.Polygon.HarmonicBinaryPrefix.zero_time_prefix
#check NewtonLimitDynamics.Polygon.HarmonicComparison.cell_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicComparison.cell_bound
#check NewtonLimitDynamics.Polygon.HarmonicComparison.cell_difference
#print axioms NewtonLimitDynamics.Polygon.HarmonicComparison.cell_difference
#check NewtonLimitDynamics.Polygon.HarmonicComparison.cell_eq_kick_drift
#print axioms NewtonLimitDynamics.Polygon.HarmonicComparison.cell_eq_kick_drift
#check NewtonLimitDynamics.Polygon.HarmonicComparison.cell_perturbation
#print axioms NewtonLimitDynamics.Polygon.HarmonicComparison.cell_perturbation
#check NewtonLimitDynamics.Polygon.HarmonicComparison.drift_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicComparison.drift_bound
#check NewtonLimitDynamics.Polygon.HarmonicComparison.kick_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicComparison.kick_bound
#check NewtonLimitDynamics.Polygon.HarmonicComparison.sample_cell_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicComparison.sample_cell_bound
#check NewtonLimitDynamics.Polygon.HarmonicComparison.sample_cell_norm
#print axioms NewtonLimitDynamics.Polygon.HarmonicComparison.sample_cell_norm
#check NewtonLimitDynamics.Polygon.HarmonicComparison.sample_initial_norm
#print axioms NewtonLimitDynamics.Polygon.HarmonicComparison.sample_initial_norm
#check NewtonLimitDynamics.Polygon.HarmonicComparison.sample_kappa
#print axioms NewtonLimitDynamics.Polygon.HarmonicComparison.sample_kappa
#check NewtonLimitDynamics.Polygon.HarmonicComparison.zero_kappa
#print axioms NewtonLimitDynamics.Polygon.HarmonicComparison.zero_kappa
#check NewtonLimitDynamics.Polygon.HarmonicComparison.zero_step
#print axioms NewtonLimitDynamics.Polygon.HarmonicComparison.zero_step
#check NewtonLimitDynamics.Polygon.HarmonicComparison.zero_step_norm
#print axioms NewtonLimitDynamics.Polygon.HarmonicComparison.zero_step_norm
#check NewtonLimitDynamics.Polygon.HarmonicCover.actual_corners_in_ball
#print axioms NewtonLimitDynamics.Polygon.HarmonicCover.actual_corners_in_ball
#check NewtonLimitDynamics.Polygon.HarmonicCover.coverBudget_formula
#print axioms NewtonLimitDynamics.Polygon.HarmonicCover.coverBudget_formula
#check NewtonLimitDynamics.Polygon.HarmonicCover.coverBudget_nonnegative
#print axioms NewtonLimitDynamics.Polygon.HarmonicCover.coverBudget_nonnegative
#check NewtonLimitDynamics.Polygon.HarmonicCover.firstPatch_square
#print axioms NewtonLimitDynamics.Polygon.HarmonicCover.firstPatch_square
#check NewtonLimitDynamics.Polygon.HarmonicCover.radius_formula
#print axioms NewtonLimitDynamics.Polygon.HarmonicCover.radius_formula
#check NewtonLimitDynamics.Polygon.HarmonicCover.radius_nonnegative
#print axioms NewtonLimitDynamics.Polygon.HarmonicCover.radius_nonnegative
#check NewtonLimitDynamics.Polygon.HarmonicCover.sample_all_corners
#print axioms NewtonLimitDynamics.Polygon.HarmonicCover.sample_all_corners
#check NewtonLimitDynamics.Polygon.HarmonicCover.sample_cover_budget
#print axioms NewtonLimitDynamics.Polygon.HarmonicCover.sample_cover_budget
#check NewtonLimitDynamics.Polygon.HarmonicCover.sample_eighth_square_too_small
#print axioms NewtonLimitDynamics.Polygon.HarmonicCover.sample_eighth_square_too_small
#check NewtonLimitDynamics.Polygon.HarmonicCover.sample_first_patch_square
#print axioms NewtonLimitDynamics.Polygon.HarmonicCover.sample_first_patch_square
#check NewtonLimitDynamics.Polygon.HarmonicCover.sample_quarter_ball_too_small
#print axioms NewtonLimitDynamics.Polygon.HarmonicCover.sample_quarter_ball_too_small
#check NewtonLimitDynamics.Polygon.HarmonicCover.sample_radius
#print axioms NewtonLimitDynamics.Polygon.HarmonicCover.sample_radius
#check NewtonLimitDynamics.Polygon.HarmonicCover.sample_second_patch_square
#print axioms NewtonLimitDynamics.Polygon.HarmonicCover.sample_second_patch_square
#check NewtonLimitDynamics.Polygon.HarmonicCover.sample_small_time
#print axioms NewtonLimitDynamics.Polygon.HarmonicCover.sample_small_time
#check NewtonLimitDynamics.Polygon.HarmonicCover.sample_square_area
#print axioms NewtonLimitDynamics.Polygon.HarmonicCover.sample_square_area
#check NewtonLimitDynamics.Polygon.HarmonicCover.sample_zero_blocks_budget
#print axioms NewtonLimitDynamics.Polygon.HarmonicCover.sample_zero_blocks_budget
#check NewtonLimitDynamics.Polygon.HarmonicCover.sample_zero_duration_budget
#print axioms NewtonLimitDynamics.Polygon.HarmonicCover.sample_zero_duration_budget
#check NewtonLimitDynamics.Polygon.HarmonicCover.secondPatch_square
#print axioms NewtonLimitDynamics.Polygon.HarmonicCover.secondPatch_square
#check NewtonLimitDynamics.Polygon.HarmonicCover.squareArea_nonnegative
#print axioms NewtonLimitDynamics.Polygon.HarmonicCover.squareArea_nonnegative
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.adjacentCap_tail
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.adjacentCap_tail
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.adjacent_error_le
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.adjacent_error_le
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.blocks_succ
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.blocks_succ
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.coefficient_nonnegative
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.coefficient_nonnegative
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.doubleTail_lt_tolerance
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.doubleTail_lt_tolerance
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.duration_halving
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.duration_halving
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.dyadic_smallTime
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.dyadic_smallTime
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.elapsed_replicate_congr
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.elapsed_replicate_congr
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.endpoint_cauchy
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.endpoint_cauchy
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.endpoint_coarse
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.endpoint_coarse
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.endpoint_elapsed
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.endpoint_elapsed
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.endpoint_fine
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.endpoint_fine
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.endpoint_next_elapsed
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.endpoint_next_elapsed
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.fineDurations_replicate
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.fineDurations_replicate
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.finite_gap_error
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.finite_gap_error
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.neg_equiv
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.neg_equiv
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.sample_adjacent_cap
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.sample_adjacent_cap
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.sample_adjacent_error
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.sample_adjacent_error
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.sample_dyadic_small_time
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.sample_dyadic_small_time
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.sample_tail_cap
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.sample_tail_cap
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.schedule_replicate_congr
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.schedule_replicate_congr
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.stateSub_congr
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.stateSub_congr
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.stateSub_norm_symm
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.stateSub_norm_symm
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.tail_double
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.tail_double
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.tail_halving
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.tail_halving
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.totalTime_dyadic
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.totalTime_dyadic
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.two_pow_ge_succ
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.two_pow_ge_succ
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.two_sided_error
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.two_sided_error
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.zero_duration_schedule
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.zero_duration_schedule
#check NewtonLimitDynamics.Polygon.HarmonicDyadic.zero_time_endpoint
#print axioms NewtonLimitDynamics.Polygon.HarmonicDyadic.zero_time_endpoint
#check NewtonLimitDynamics.Polygon.HarmonicRefinement.absoluteClosedGap_nonnegative
#print axioms NewtonLimitDynamics.Polygon.HarmonicRefinement.absoluteClosedGap_nonnegative
#check NewtonLimitDynamics.Polygon.HarmonicRefinement.absolute_closed_defect_cubic
#print axioms NewtonLimitDynamics.Polygon.HarmonicRefinement.absolute_closed_defect_cubic
#check NewtonLimitDynamics.Polygon.HarmonicRefinement.closed_defect_cubic
#print axioms NewtonLimitDynamics.Polygon.HarmonicRefinement.closed_defect_cubic
#check NewtonLimitDynamics.Polygon.HarmonicRefinement.closed_eq_triangle
#print axioms NewtonLimitDynamics.Polygon.HarmonicRefinement.closed_eq_triangle
#check NewtonLimitDynamics.Polygon.HarmonicRefinement.position_mismatch
#print axioms NewtonLimitDynamics.Polygon.HarmonicRefinement.position_mismatch
#check NewtonLimitDynamics.Polygon.HarmonicRefinement.sample_absolute_closed_gap
#print axioms NewtonLimitDynamics.Polygon.HarmonicRefinement.sample_absolute_closed_gap
#check NewtonLimitDynamics.Polygon.HarmonicRefinement.sample_closed_defect
#print axioms NewtonLimitDynamics.Polygon.HarmonicRefinement.sample_closed_defect
#check NewtonLimitDynamics.Polygon.HarmonicRefinement.sample_closed_defect_nonzero
#print axioms NewtonLimitDynamics.Polygon.HarmonicRefinement.sample_closed_defect_nonzero
#check NewtonLimitDynamics.Polygon.HarmonicRefinement.sample_coarse
#print axioms NewtonLimitDynamics.Polygon.HarmonicRefinement.sample_coarse
#check NewtonLimitDynamics.Polygon.HarmonicRefinement.sample_coarse_swept
#print axioms NewtonLimitDynamics.Polygon.HarmonicRefinement.sample_coarse_swept
#check NewtonLimitDynamics.Polygon.HarmonicRefinement.sample_fine
#print axioms NewtonLimitDynamics.Polygon.HarmonicRefinement.sample_fine
#check NewtonLimitDynamics.Polygon.HarmonicRefinement.sample_fine_swept
#print axioms NewtonLimitDynamics.Polygon.HarmonicRefinement.sample_fine_swept
#check NewtonLimitDynamics.Polygon.HarmonicRefinement.sample_middle
#print axioms NewtonLimitDynamics.Polygon.HarmonicRefinement.sample_middle
#check NewtonLimitDynamics.Polygon.HarmonicRefinement.swept_equal
#print axioms NewtonLimitDynamics.Polygon.HarmonicRefinement.swept_equal
#check NewtonLimitDynamics.Polygon.HarmonicRefinement.velocity_mismatch
#print axioms NewtonLimitDynamics.Polygon.HarmonicRefinement.velocity_mismatch
#check NewtonLimitDynamics.Polygon.HarmonicStability.cell_invariant
#print axioms NewtonLimitDynamics.Polygon.HarmonicStability.cell_invariant
#check NewtonLimitDynamics.Polygon.HarmonicStability.dot_self_num_nonneg
#print axioms NewtonLimitDynamics.Polygon.HarmonicStability.dot_self_num_nonneg
#check NewtonLimitDynamics.Polygon.HarmonicStability.invariant_square
#print axioms NewtonLimitDynamics.Polygon.HarmonicStability.invariant_square
#check NewtonLimitDynamics.Polygon.HarmonicStability.linearField_central
#print axioms NewtonLimitDynamics.Polygon.HarmonicStability.linearField_central
#check NewtonLimitDynamics.Polygon.HarmonicStability.position_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicStability.position_bound
#check NewtonLimitDynamics.Polygon.HarmonicStability.schedule_invariant
#print axioms NewtonLimitDynamics.Polygon.HarmonicStability.schedule_invariant
#check NewtonLimitDynamics.Polygon.HarmonicStability.schedule_position_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicStability.schedule_position_bound
#check NewtonLimitDynamics.Polygon.HarmonicStability.schedule_speed_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicStability.schedule_speed_bound
#check NewtonLimitDynamics.Polygon.HarmonicStability.speed_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicStability.speed_bound
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.actual_coarse_parameter_error
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.actual_coarse_parameter_error
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.actual_coarse_parameter_uniform
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.actual_coarse_parameter_uniform
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.cell_parameter_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.cell_parameter_bound
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.cell_parameter_difference
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.cell_parameter_difference
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.cell_parameter_norm_formula
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.cell_parameter_norm_formula
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.coarse_parameter_step
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.coarse_parameter_step
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.count_abs_duration_difference
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.count_abs_duration_difference
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.count_duration_difference
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.count_duration_difference
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.duration_le_time
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.duration_le_time
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.dyadic_time_le_half
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.dyadic_time_le_half
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.endpoint_time_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.endpoint_time_bound
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.parameter_budget_power
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.parameter_budget_power
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.parameter_delta_control
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.parameter_delta_control
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.same_time_error_zero
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.same_time_error_zero
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.sample_parameter_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.sample_parameter_bound
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.sample_parameter_error
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.sample_parameter_error
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.sample_short_times
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.sample_short_times
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.sample_time_budget
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.sample_time_budget
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.sample_time_lipschitz
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.sample_time_lipschitz
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.short_duration_pair
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.short_duration_pair
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.short_sum_point_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.short_sum_point_bound
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.timeDelta_positive
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.timeDelta_positive
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.timeLipschitz_nonnegative
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.timeLipschitz_nonnegative
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.timeName_uniform_continuity
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.timeName_uniform_continuity
#check NewtonLimitDynamics.Polygon.HarmonicTimeComparison.zero_state_error_zero
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeComparison.zero_state_error_zero
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.address_state_equiv
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.address_state_equiv
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.alias_address_equiv
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.alias_address_equiv
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.alias_ticks
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.alias_ticks
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.alias_time_distance
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.alias_time_distance
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.alias_time_eq
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.alias_time_eq
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.alias_value_eq
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.alias_value_eq
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.countState_coarse
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.countState_coarse
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.countState_gap
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.countState_gap
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.countState_le_two
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.countState_le_two
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.countState_ordered_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.countState_ordered_bound
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.countState_same_grid_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.countState_same_grid_bound
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.countState_step_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.countState_step_bound
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.countTime_abs_difference
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.countTime_abs_difference
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.countTime_difference
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.countTime_difference
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.durationDifference_abs_symm
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.durationDifference_abs_symm
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.duration_eventually_small
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.duration_eventually_small
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.duration_factor_eventually_small
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.duration_factor_eventually_small
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.factorDelta_positive
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.factorDelta_positive
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.factorDenominator_positive
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.factorDenominator_positive
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.factor_control
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.factor_control
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.factor_delta_weak
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.factor_delta_weak
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.gammaValue_address
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.gammaValue_address
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.gamma_uniform_continuity
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.gamma_uniform_continuity
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.gamma_within
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.gamma_within
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.left_endpoint_value
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.left_endpoint_value
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.left_time_coordinate
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.left_time_coordinate
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.left_time_state_equiv
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.left_time_state_equiv
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.nameBound_mono
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.nameBound_mono
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.nameBound_scale
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.nameBound_scale
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.prefix_time_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.prefix_time_bound
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.right_endpoint_value
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.right_endpoint_value
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.right_prefix_endpoint_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.right_prefix_endpoint_bound
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.right_ticks
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.right_ticks
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.right_time_coordinate
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.right_time_coordinate
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.right_time_difference
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.right_time_difference
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.right_time_distance
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.right_time_distance
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.sample_alias_actual_error
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.sample_alias_actual_error
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.sample_alias_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.sample_alias_bound
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.sample_alias_counts
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.sample_alias_counts
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.sample_alias_time_gap
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.sample_alias_time_gap
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.sample_right_ne_left
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.sample_right_ne_left
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.sample_state_time_factor
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.sample_state_time_factor
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.stateTimeFactor_nonnegative
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.stateTimeFactor_nonnegative
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.timeCoordinate_injective
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.timeCoordinate_injective
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.timeTolerance_positive
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.timeTolerance_positive
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.timeWithin_address
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.timeWithin_address
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.within_mono
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.within_mono
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.zero_state_norm_value
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.zero_state_norm_value
#check NewtonLimitDynamics.Polygon.HarmonicTimeRealization.zero_time_value
#print axioms NewtonLimitDynamics.Polygon.HarmonicTimeRealization.zero_time_value
#check NewtonLimitDynamics.Polygon.HarmonicUniform.actual_uniform_error
#print axioms NewtonLimitDynamics.Polygon.HarmonicUniform.actual_uniform_error
#check NewtonLimitDynamics.Polygon.HarmonicUniform.coarseFactor_le_fineFactor
#print axioms NewtonLimitDynamics.Polygon.HarmonicUniform.coarseFactor_le_fineFactor
#check NewtonLimitDynamics.Polygon.HarmonicUniform.coarse_elapsed_totalTime
#print axioms NewtonLimitDynamics.Polygon.HarmonicUniform.coarse_elapsed_totalTime
#check NewtonLimitDynamics.Polygon.HarmonicUniform.coarse_power_le_two
#print axioms NewtonLimitDynamics.Polygon.HarmonicUniform.coarse_power_le_two
#check NewtonLimitDynamics.Polygon.HarmonicUniform.coarse_state_le_two
#print axioms NewtonLimitDynamics.Polygon.HarmonicUniform.coarse_state_le_two
#check NewtonLimitDynamics.Polygon.HarmonicUniform.false_unrestricted_power
#print axioms NewtonLimitDynamics.Polygon.HarmonicUniform.false_unrestricted_power
#check NewtonLimitDynamics.Polygon.HarmonicUniform.fine_elapsed_totalTime
#print axioms NewtonLimitDynamics.Polygon.HarmonicUniform.fine_elapsed_totalTime
#check NewtonLimitDynamics.Polygon.HarmonicUniform.fine_norm_bound
#print axioms NewtonLimitDynamics.Polygon.HarmonicUniform.fine_norm_bound
#check NewtonLimitDynamics.Polygon.HarmonicUniform.fine_power_le_two
#print axioms NewtonLimitDynamics.Polygon.HarmonicUniform.fine_power_le_two
#check NewtonLimitDynamics.Polygon.HarmonicUniform.fine_state_le_two
#print axioms NewtonLimitDynamics.Polygon.HarmonicUniform.fine_state_le_two
#check NewtonLimitDynamics.Polygon.HarmonicUniform.one_le_kappa
#print axioms NewtonLimitDynamics.Polygon.HarmonicUniform.one_le_kappa
#check NewtonLimitDynamics.Polygon.HarmonicUniform.one_le_power
#print axioms NewtonLimitDynamics.Polygon.HarmonicUniform.one_le_power
#check NewtonLimitDynamics.Polygon.HarmonicUniform.sample_actual_error
#print axioms NewtonLimitDynamics.Polygon.HarmonicUniform.sample_actual_error
#check NewtonLimitDynamics.Polygon.HarmonicUniform.sample_power_bounds
#print axioms NewtonLimitDynamics.Polygon.HarmonicUniform.sample_power_bounds
#check NewtonLimitDynamics.Polygon.HarmonicUniform.sample_small_time
#print axioms NewtonLimitDynamics.Polygon.HarmonicUniform.sample_small_time
#check NewtonLimitDynamics.Polygon.HarmonicUniform.sample_total_time
#print axioms NewtonLimitDynamics.Polygon.HarmonicUniform.sample_total_time
#check NewtonLimitDynamics.Polygon.HarmonicUniform.sample_uniform_error
#print axioms NewtonLimitDynamics.Polygon.HarmonicUniform.sample_uniform_error
#check NewtonLimitDynamics.Polygon.HarmonicUniform.sample_uniform_rhs
#print axioms NewtonLimitDynamics.Polygon.HarmonicUniform.sample_uniform_rhs
#check NewtonLimitDynamics.Polygon.HarmonicUniform.sample_zero_blocks
#print axioms NewtonLimitDynamics.Polygon.HarmonicUniform.sample_zero_blocks
#check NewtonLimitDynamics.Polygon.HarmonicUniform.sample_zero_duration
#print axioms NewtonLimitDynamics.Polygon.HarmonicUniform.sample_zero_duration
#check NewtonLimitDynamics.Polygon.HarmonicUniform.smallTime_prefix
#print axioms NewtonLimitDynamics.Polygon.HarmonicUniform.smallTime_prefix
#check NewtonLimitDynamics.Polygon.HarmonicUniform.two_mul
#print axioms NewtonLimitDynamics.Polygon.HarmonicUniform.two_mul
#check NewtonLimitDynamics.Polygon.InertialControl.drift_small
#print axioms NewtonLimitDynamics.Polygon.InertialControl.drift_small
#check NewtonLimitDynamics.Polygon.InertialControl.endKick_zero_small_increment
#print axioms NewtonLimitDynamics.Polygon.InertialControl.endKick_zero_small_increment
#check NewtonLimitDynamics.Polygon.InertialControl.exists_uniform_inertial_radius
#print axioms NewtonLimitDynamics.Polygon.InertialControl.exists_uniform_inertial_radius
#check NewtonLimitDynamics.Polygon.InertialControl.inertialAt_small_increment
#print axioms NewtonLimitDynamics.Polygon.InertialControl.inertialAt_small_increment
#check NewtonLimitDynamics.Polygon.InertialControl.radius_positive
#print axioms NewtonLimitDynamics.Polygon.InertialControl.radius_positive
#check NewtonLimitDynamics.Polygon.InertialDefect.closedBoundaryTwice_congr
#print axioms NewtonLimitDynamics.Polygon.InertialDefect.closedBoundaryTwice_congr
#check NewtonLimitDynamics.Polygon.InertialDefect.det_congr
#print axioms NewtonLimitDynamics.Polygon.InertialDefect.det_congr
#check NewtonLimitDynamics.Polygon.InertialDefect.inertialEdge_compose
#print axioms NewtonLimitDynamics.Polygon.InertialDefect.inertialEdge_compose
#check NewtonLimitDynamics.Polygon.InertialDefect.inertialEdge_self
#print axioms NewtonLimitDynamics.Polygon.InertialDefect.inertialEdge_self
#check NewtonLimitDynamics.Polygon.InertialDefect.inertialWalk_closed
#print axioms NewtonLimitDynamics.Polygon.InertialDefect.inertialWalk_closed
#check NewtonLimitDynamics.Polygon.InertialDefect.inertialWalk_eq_edge
#print axioms NewtonLimitDynamics.Polygon.InertialDefect.inertialWalk_eq_edge
#check NewtonLimitDynamics.Polygon.InertialDefect.inertial_closedBoundaryTwice
#print axioms NewtonLimitDynamics.Polygon.InertialDefect.inertial_closedBoundaryTwice
#check NewtonLimitDynamics.Polygon.InertialDefect.partitionMotion_closedBoundaryTwice
#print axioms NewtonLimitDynamics.Polygon.InertialDefect.partitionMotion_closedBoundaryTwice
#check NewtonLimitDynamics.Polygon.MonotoneEnclosure.antitone_enclosure
#print axioms NewtonLimitDynamics.Polygon.MonotoneEnclosure.antitone_enclosure
#check NewtonLimitDynamics.Polygon.MonotoneEnclosure.enclosure
#print axioms NewtonLimitDynamics.Polygon.MonotoneEnclosure.enclosure
#check NewtonLimitDynamics.Polygon.MonotoneEnclosure.monotone_enclosure
#print axioms NewtonLimitDynamics.Polygon.MonotoneEnclosure.monotone_enclosure
#check NewtonLimitDynamics.Polygon.MonotoneEnclosure.nonmonotone_escapes
#print axioms NewtonLimitDynamics.Polygon.MonotoneEnclosure.nonmonotone_escapes
#check NewtonLimitDynamics.Polygon.MonotoneEnclosure.pos_const
#print axioms NewtonLimitDynamics.Polygon.MonotoneEnclosure.pos_const
#check NewtonLimitDynamics.Polygon.MonotoneEnclosure.vel_bounds
#print axioms NewtonLimitDynamics.Polygon.MonotoneEnclosure.vel_bounds
#check NewtonLimitDynamics.Polygon.PartialCell.candidate_partial_residual
#print axioms NewtonLimitDynamics.Polygon.PartialCell.candidate_partial_residual
#check NewtonLimitDynamics.Polygon.PartialCell.endKick_position_kick_free
#print axioms NewtonLimitDynamics.Polygon.PartialCell.endKick_position_kick_free
#check NewtonLimitDynamics.Polygon.PartialCell.partialState_append
#print axioms NewtonLimitDynamics.Polygon.PartialCell.partialState_append
#check NewtonLimitDynamics.Polygon.PartialCell.partialState_position
#print axioms NewtonLimitDynamics.Polygon.PartialCell.partialState_position
#check NewtonLimitDynamics.Polygon.PartialCell.partial_full_cell
#print axioms NewtonLimitDynamics.Polygon.PartialCell.partial_full_cell
#check NewtonLimitDynamics.Polygon.PartialCell.partial_residual_mesh_bound
#print axioms NewtonLimitDynamics.Polygon.PartialCell.partial_residual_mesh_bound
#check NewtonLimitDynamics.Polygon.PartialCell.partial_squares_bound
#print axioms NewtonLimitDynamics.Polygon.PartialCell.partial_squares_bound
#check NewtonLimitDynamics.Polygon.PartialCell.partial_zero
#print axioms NewtonLimitDynamics.Polygon.PartialCell.partial_zero
#check NewtonLimitDynamics.Polygon.PartialCell.partial_zero_force
#print axioms NewtonLimitDynamics.Polygon.PartialCell.partial_zero_force
#check NewtonLimitDynamics.Polygon.PartialCell.squares_append
#print axioms NewtonLimitDynamics.Polygon.PartialCell.squares_append
#check NewtonLimitDynamics.Polygon.PartialCell.stats_append
#print axioms NewtonLimitDynamics.Polygon.PartialCell.stats_append
#check NewtonLimitDynamics.Polygon.PartialCell.total_append
#print axioms NewtonLimitDynamics.Polygon.PartialCell.total_append
#check NewtonLimitDynamics.Polygon.PartitionComparison.candidate_time_congr
#print axioms NewtonLimitDynamics.Polygon.PartitionComparison.candidate_time_congr
#check NewtonLimitDynamics.Polygon.PartitionComparison.partial_comparison
#print axioms NewtonLimitDynamics.Polygon.PartitionComparison.partial_comparison
#check NewtonLimitDynamics.Polygon.PartitionComparison.partition_comparison
#print axioms NewtonLimitDynamics.Polygon.PartitionComparison.partition_comparison
#check NewtonLimitDynamics.Polygon.PartitionComparison.partition_gap
#print axioms NewtonLimitDynamics.Polygon.PartitionComparison.partition_gap
#check NewtonLimitDynamics.Polygon.PartitionComparison.velocity_comparison
#print axioms NewtonLimitDynamics.Polygon.PartitionComparison.velocity_comparison
#check NewtonLimitDynamics.Polygon.PartitionControl.candidate_partitionMotion_residual
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.candidate_partitionMotion_residual
#check NewtonLimitDynamics.Polygon.PartitionControl.candidate_residual
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.candidate_residual
#check NewtonLimitDynamics.Polygon.PartitionControl.duration_positive
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.duration_positive
#check NewtonLimitDynamics.Polygon.PartitionControl.next_bound
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.next_bound
#check NewtonLimitDynamics.Polygon.PartitionControl.next_identity
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.next_identity
#check NewtonLimitDynamics.Polygon.PartitionControl.partitionMotion_formula
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.partitionMotion_formula
#check NewtonLimitDynamics.Polygon.PartitionControl.residual_mesh_bound
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.residual_mesh_bound
#check NewtonLimitDynamics.Polygon.PartitionControl.residual_nonnegative
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.residual_nonnegative
#check NewtonLimitDynamics.Polygon.PartitionControl.stats_bound
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.stats_bound
#check NewtonLimitDynamics.Polygon.PartitionControl.stats_bound_from
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.stats_bound_from
#check NewtonLimitDynamics.Polygon.PartitionControl.stats_identity
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.stats_identity
#check NewtonLimitDynamics.Polygon.PartitionControl.stats_identity_from
#print axioms NewtonLimitDynamics.Polygon.PartitionControl.stats_identity_from
#check NewtonLimitDynamics.Polygon.PathDefect.absolute_budget_le_count_mul
#print axioms NewtonLimitDynamics.Polygon.PathDefect.absolute_budget_le_count_mul
#check NewtonLimitDynamics.Polygon.PathDefect.absolute_budget_translation
#print axioms NewtonLimitDynamics.Polygon.PathDefect.absolute_budget_translation
#check NewtonLimitDynamics.Polygon.PathDefect.equal_Kepler_areas_positive_path_defect
#print axioms NewtonLimitDynamics.Polygon.PathDefect.equal_Kepler_areas_positive_path_defect
#check NewtonLimitDynamics.Polygon.PathDefect.polygon_trajectory_defect_vanishes
#print axioms NewtonLimitDynamics.Polygon.PathDefect.polygon_trajectory_defect_vanishes
#check NewtonLimitDynamics.Polygon.PathDefect.signed_gap_abs_le_budget
#print axioms NewtonLimitDynamics.Polygon.PathDefect.signed_gap_abs_le_budget
#check NewtonLimitDynamics.Polygon.PathDefect.signed_gap_eq_Kepler_difference
#print axioms NewtonLimitDynamics.Polygon.PathDefect.signed_gap_eq_Kepler_difference
#check NewtonLimitDynamics.Polygon.PointBounds.pointNorm_add_le
#print axioms NewtonLimitDynamics.Polygon.PointBounds.pointNorm_add_le
#check NewtonLimitDynamics.Polygon.PointBounds.pointNorm_equiv
#print axioms NewtonLimitDynamics.Polygon.PointBounds.pointNorm_equiv
#check NewtonLimitDynamics.Polygon.PointBounds.pointNorm_nonnegative
#print axioms NewtonLimitDynamics.Polygon.PointBounds.pointNorm_nonnegative
#check NewtonLimitDynamics.Polygon.PointBounds.pointNorm_scale
#print axioms NewtonLimitDynamics.Polygon.PointBounds.pointNorm_scale
#check NewtonLimitDynamics.Polygon.PointBounds.point_le_state
#print axioms NewtonLimitDynamics.Polygon.PointBounds.point_le_state
#check NewtonLimitDynamics.Polygon.PointBounds.stateNorm_add_le
#print axioms NewtonLimitDynamics.Polygon.PointBounds.stateNorm_add_le
#check NewtonLimitDynamics.Polygon.PointBounds.stateNorm_equiv
#print axioms NewtonLimitDynamics.Polygon.PointBounds.stateNorm_equiv
#check NewtonLimitDynamics.Polygon.PointBounds.stateNorm_nonnegative
#print axioms NewtonLimitDynamics.Polygon.PointBounds.stateNorm_nonnegative
#check NewtonLimitDynamics.Polygon.PointBounds.stateNorm_scale
#print axioms NewtonLimitDynamics.Polygon.PointBounds.stateNorm_scale
#check NewtonLimitDynamics.Polygon.PointBounds.velocity_le_state
#print axioms NewtonLimitDynamics.Polygon.PointBounds.velocity_le_state
#check NewtonLimitDynamics.Polygon.PositionValues.firstValue_embed
#print axioms NewtonLimitDynamics.Polygon.PositionValues.firstValue_embed
#check NewtonLimitDynamics.Polygon.PositionValues.firstValue_positionValue
#print axioms NewtonLimitDynamics.Polygon.PositionValues.firstValue_positionValue
#check NewtonLimitDynamics.Polygon.PositionValues.firstValue_within
#print axioms NewtonLimitDynamics.Polygon.PositionValues.firstValue_within
#check NewtonLimitDynamics.Polygon.PositionValues.first_nonexpansive
#print axioms NewtonLimitDynamics.Polygon.PositionValues.first_nonexpansive
#check NewtonLimitDynamics.Polygon.PositionValues.gammaPosition_alias
#print axioms NewtonLimitDynamics.Polygon.PositionValues.gammaPosition_alias
#check NewtonLimitDynamics.Polygon.PositionValues.gammaPosition_left
#print axioms NewtonLimitDynamics.Polygon.PositionValues.gammaPosition_left
#check NewtonLimitDynamics.Polygon.PositionValues.gammaPosition_right
#print axioms NewtonLimitDynamics.Polygon.PositionValues.gammaPosition_right
#check NewtonLimitDynamics.Polygon.PositionValues.gammaPosition_uniform_continuity
#print axioms NewtonLimitDynamics.Polygon.PositionValues.gammaPosition_uniform_continuity
#check NewtonLimitDynamics.Polygon.PositionValues.gammaPosition_within
#print axioms NewtonLimitDynamics.Polygon.PositionValues.gammaPosition_within
#check NewtonLimitDynamics.Polygon.PositionValues.gammaPosition_zero_state_norm
#print axioms NewtonLimitDynamics.Polygon.PositionValues.gammaPosition_zero_state_norm
#check NewtonLimitDynamics.Polygon.PositionValues.gammaPosition_zero_time
#print axioms NewtonLimitDynamics.Polygon.PositionValues.gammaPosition_zero_time
#check NewtonLimitDynamics.Polygon.PositionValues.mapName_bound
#print axioms NewtonLimitDynamics.Polygon.PositionValues.mapName_bound
#check NewtonLimitDynamics.Polygon.PositionValues.mapName_equiv
#print axioms NewtonLimitDynamics.Polygon.PositionValues.mapName_equiv
#check NewtonLimitDynamics.Polygon.PositionValues.mapValue_embed
#print axioms NewtonLimitDynamics.Polygon.PositionValues.mapValue_embed
#check NewtonLimitDynamics.Polygon.PositionValues.mapValue_within
#print axioms NewtonLimitDynamics.Polygon.PositionValues.mapValue_within
#check NewtonLimitDynamics.Polygon.PositionValues.positionValue_embed
#print axioms NewtonLimitDynamics.Polygon.PositionValues.positionValue_embed
#check NewtonLimitDynamics.Polygon.PositionValues.positionValue_idempotent
#print axioms NewtonLimitDynamics.Polygon.PositionValues.positionValue_idempotent
#check NewtonLimitDynamics.Polygon.PositionValues.positionValue_within
#print axioms NewtonLimitDynamics.Polygon.PositionValues.positionValue_within
#check NewtonLimitDynamics.Polygon.PositionValues.position_nonexpansive
#print axioms NewtonLimitDynamics.Polygon.PositionValues.position_nonexpansive
#check NewtonLimitDynamics.Polygon.PositionValues.sample_corner_L1_distance_two
#print axioms NewtonLimitDynamics.Polygon.PositionValues.sample_corner_L1_distance_two
#check NewtonLimitDynamics.Polygon.PositionValues.sample_corner_in_square
#print axioms NewtonLimitDynamics.Polygon.PositionValues.sample_corner_in_square
#check NewtonLimitDynamics.Polygon.PositionValues.sample_endpoint_position_ne_initial
#print axioms NewtonLimitDynamics.Polygon.PositionValues.sample_endpoint_position_ne_initial
#check NewtonLimitDynamics.Polygon.PositionValues.sample_gammaPosition_right_ne_left
#print axioms NewtonLimitDynamics.Polygon.PositionValues.sample_gammaPosition_right_ne_left
#check NewtonLimitDynamics.Polygon.PositionValues.sample_position_level_one
#print axioms NewtonLimitDynamics.Polygon.PositionValues.sample_position_level_one
#check NewtonLimitDynamics.Polygon.PositionValues.sample_position_lower_all_levels
#print axioms NewtonLimitDynamics.Polygon.PositionValues.sample_position_lower_all_levels
#check NewtonLimitDynamics.Polygon.PositionValues.sample_tail_one
#print axioms NewtonLimitDynamics.Polygon.PositionValues.sample_tail_one
#check NewtonLimitDynamics.Polygon.PositionValues.secondValue_embed
#print axioms NewtonLimitDynamics.Polygon.PositionValues.secondValue_embed
#check NewtonLimitDynamics.Polygon.PositionValues.secondValue_positionValue
#print axioms NewtonLimitDynamics.Polygon.PositionValues.secondValue_positionValue
#check NewtonLimitDynamics.Polygon.PositionValues.secondValue_within
#print axioms NewtonLimitDynamics.Polygon.PositionValues.secondValue_within
#check NewtonLimitDynamics.Polygon.PositionValues.second_nonexpansive
#print axioms NewtonLimitDynamics.Polygon.PositionValues.second_nonexpansive
#check NewtonLimitDynamics.Polygon.PositionValues.square_of_eventual_coordinate_bounds
#print axioms NewtonLimitDynamics.Polygon.PositionValues.square_of_eventual_coordinate_bounds
#check NewtonLimitDynamics.Polygon.PositionValues.square_of_rational_coordinate_bounds
#print axioms NewtonLimitDynamics.Polygon.PositionValues.square_of_rational_coordinate_bounds
#check NewtonLimitDynamics.Polygon.RelativeMotion.absolute_deflection
#print axioms NewtonLimitDynamics.Polygon.RelativeMotion.absolute_deflection
#check NewtonLimitDynamics.Polygon.RelativeMotion.add_common_cancel
#print axioms NewtonLimitDynamics.Polygon.RelativeMotion.add_common_cancel
#check NewtonLimitDynamics.Polygon.RelativeMotion.add_sub_distrib
#print axioms NewtonLimitDynamics.Polygon.RelativeMotion.add_sub_distrib
#check NewtonLimitDynamics.Polygon.RelativeMotion.add_zero_right
#print axioms NewtonLimitDynamics.Polygon.RelativeMotion.add_zero_right
#check NewtonLimitDynamics.Polygon.RelativeMotion.centre_is_reference_body
#print axioms NewtonLimitDynamics.Polygon.RelativeMotion.centre_is_reference_body
#check NewtonLimitDynamics.Polygon.RelativeMotion.common_deflection_example
#print axioms NewtonLimitDynamics.Polygon.RelativeMotion.common_deflection_example
#check NewtonLimitDynamics.Polygon.RelativeMotion.corVI_relative
#print axioms NewtonLimitDynamics.Polygon.RelativeMotion.corVI_relative
#check NewtonLimitDynamics.Polygon.RelativeMotion.det_add
#print axioms NewtonLimitDynamics.Polygon.RelativeMotion.det_add
#check NewtonLimitDynamics.Polygon.RelativeMotion.difference_not_pair_example
#print axioms NewtonLimitDynamics.Polygon.RelativeMotion.difference_not_pair_example
#check NewtonLimitDynamics.Polygon.RelativeMotion.extend_sub
#print axioms NewtonLimitDynamics.Polygon.RelativeMotion.extend_sub
#check NewtonLimitDynamics.Polygon.RelativeMotion.lawI_uniform
#print axioms NewtonLimitDynamics.Polygon.RelativeMotion.lawI_uniform
#check NewtonLimitDynamics.Polygon.RelativeMotion.moving_centre_alignment_example
#print axioms NewtonLimitDynamics.Polygon.RelativeMotion.moving_centre_alignment_example
#check NewtonLimitDynamics.Polygon.RelativeMotion.propIII_via_moving_centre
#print axioms NewtonLimitDynamics.Polygon.RelativeMotion.propIII_via_moving_centre
#check NewtonLimitDynamics.Polygon.RelativeMotion.relP_succ
#print axioms NewtonLimitDynamics.Polygon.RelativeMotion.relP_succ
#check NewtonLimitDynamics.Polygon.RelativeMotion.relative_deflection_difference
#print axioms NewtonLimitDynamics.Polygon.RelativeMotion.relative_deflection_difference
#check NewtonLimitDynamics.Polygon.RelativeMotion.relative_equal_area_central
#print axioms NewtonLimitDynamics.Polygon.RelativeMotion.relative_equal_area_central
#check NewtonLimitDynamics.Polygon.RelativeMotion.relative_rational_central
#print axioms NewtonLimitDynamics.Polygon.RelativeMotion.relative_rational_central
#check NewtonLimitDynamics.Polygon.StripArea.all_triangles_equal
#print axioms NewtonLimitDynamics.Polygon.StripArea.all_triangles_equal
#check NewtonLimitDynamics.Polygon.StripArea.chord_is_position_diff
#print axioms NewtonLimitDynamics.Polygon.StripArea.chord_is_position_diff
#check NewtonLimitDynamics.Polygon.StripArea.det_kick_direction_constant
#print axioms NewtonLimitDynamics.Polygon.StripArea.det_kick_direction_constant
#check NewtonLimitDynamics.Polygon.StripArea.pointSub_add_self_left_equiv
#print axioms NewtonLimitDynamics.Polygon.StripArea.pointSub_add_self_left_equiv
#check NewtonLimitDynamics.Polygon.StripArea.total_strip_area
#print axioms NewtonLimitDynamics.Polygon.StripArea.total_strip_area
#check NewtonLimitDynamics.Polygon.StripArea.two_cell_triangle_constant
#print axioms NewtonLimitDynamics.Polygon.StripArea.two_cell_triangle_constant
#check NewtonLimitDynamics.Polygon.StripArea.vel_det_constant
#print axioms NewtonLimitDynamics.Polygon.StripArea.vel_det_constant
#check NewtonLimitDynamics.Polygon.TimeSubdivision.det_add_right
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.det_add_right
#check NewtonLimitDynamics.Polygon.TimeSubdivision.example_closedBoundaryTwice
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.example_closedBoundaryTwice
#check NewtonLimitDynamics.Polygon.TimeSubdivision.example_coarse_position
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.example_coarse_position
#check NewtonLimitDynamics.Polygon.TimeSubdivision.example_connector
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.example_connector
#check NewtonLimitDynamics.Polygon.TimeSubdivision.example_endpoints_differ
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.example_endpoints_differ
#check NewtonLimitDynamics.Polygon.TimeSubdivision.example_fine_coarse_endpoints_differ
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.example_fine_coarse_endpoints_differ
#check NewtonLimitDynamics.Polygon.TimeSubdivision.example_fine_middle
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.example_fine_middle
#check NewtonLimitDynamics.Polygon.TimeSubdivision.example_fine_position
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.example_fine_position
#check NewtonLimitDynamics.Polygon.TimeSubdivision.example_half_positive
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.example_half_positive
#check NewtonLimitDynamics.Polygon.TimeSubdivision.example_total_positive
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.example_total_positive
#check NewtonLimitDynamics.Polygon.TimeSubdivision.fine_position_eq_coarse_plus
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.fine_position_eq_coarse_plus
#check NewtonLimitDynamics.Polygon.TimeSubdivision.fine_velocity_eq_coarse
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.fine_velocity_eq_coarse
#check NewtonLimitDynamics.Polygon.TimeSubdivision.pointAdd_congr
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.pointAdd_congr
#check NewtonLimitDynamics.Polygon.TimeSubdivision.pointEquiv_symm
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.pointEquiv_symm
#check NewtonLimitDynamics.Polygon.TimeSubdivision.pointEquiv_trans
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.pointEquiv_trans
#check NewtonLimitDynamics.Polygon.TimeSubdivision.pointScale_congr
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.pointScale_congr
#check NewtonLimitDynamics.Polygon.TimeSubdivision.totalDuration_positive
#print axioms NewtonLimitDynamics.Polygon.TimeSubdivision.totalDuration_positive
#check NewtonLimitDynamics.Polygon.TriangleBounds.det_abs_le_product
#print axioms NewtonLimitDynamics.Polygon.TriangleBounds.det_abs_le_product
#check NewtonLimitDynamics.Polygon.TriangleBounds.sample_opposite_signed_sum
#print axioms NewtonLimitDynamics.Polygon.TriangleBounds.sample_opposite_signed_sum
#check NewtonLimitDynamics.Polygon.TriangleBounds.sample_opposite_unsigned_sum
#print axioms NewtonLimitDynamics.Polygon.TriangleBounds.sample_opposite_unsigned_sum
#check NewtonLimitDynamics.Polygon.TriangleBounds.sample_signed_negative
#print axioms NewtonLimitDynamics.Polygon.TriangleBounds.sample_signed_negative
#check NewtonLimitDynamics.Polygon.TriangleBounds.sample_signed_positive
#print axioms NewtonLimitDynamics.Polygon.TriangleBounds.sample_signed_positive
#check NewtonLimitDynamics.Polygon.TriangleBounds.sample_unsigned_not_signed
#print axioms NewtonLimitDynamics.Polygon.TriangleBounds.sample_unsigned_not_signed
#check NewtonLimitDynamics.Polygon.TriangleBounds.triangleMagnitude_le_consecutive
#print axioms NewtonLimitDynamics.Polygon.TriangleBounds.triangleMagnitude_le_consecutive
#check NewtonLimitDynamics.Polygon.TriangleBounds.triangleMagnitude_le_product
#print axioms NewtonLimitDynamics.Polygon.TriangleBounds.triangleMagnitude_le_product
#check NewtonLimitDynamics.Polygon.TriangleBounds.triangleMagnitude_nonnegative
#print axioms NewtonLimitDynamics.Polygon.TriangleBounds.triangleMagnitude_nonnegative
#check NewtonLimitDynamics.Polygon.TriangleBounds.triangleMagnitude_swap
#print axioms NewtonLimitDynamics.Polygon.TriangleBounds.triangleMagnitude_swap
#check NewtonLimitDynamics.Polygon.TriangleBounds.triangleMagnitude_translation
#print axioms NewtonLimitDynamics.Polygon.TriangleBounds.triangleMagnitude_translation
#check NewtonLimitDynamics.Polygon.TriangleBounds.triangleTwice_consecutive
#print axioms NewtonLimitDynamics.Polygon.TriangleBounds.triangleTwice_consecutive
#check NewtonLimitDynamics.Polygon.TriangleBounds.triangleTwice_swap
#print axioms NewtonLimitDynamics.Polygon.TriangleBounds.triangleTwice_swap
#check NewtonLimitDynamics.Polygon.TriangleBounds.triangleTwice_translation
#print axioms NewtonLimitDynamics.Polygon.TriangleBounds.triangleTwice_translation
#check NewtonLimitDynamics.Polygon.UniformRefinement.refined_time
#print axioms NewtonLimitDynamics.Polygon.UniformRefinement.refined_time
#check NewtonLimitDynamics.Polygon.UniformRefinement.uniform_refinement_small
#print axioms NewtonLimitDynamics.Polygon.UniformRefinement.uniform_refinement_small
#check NewtonLimitDynamics.Polygon.UniformRefinement.unitCells_le_one
#print axioms NewtonLimitDynamics.Polygon.UniformRefinement.unitCells_le_one
#check NewtonLimitDynamics.Polygon.UniformRefinement.unitCells_total
#print axioms NewtonLimitDynamics.Polygon.UniformRefinement.unitCells_total
#check NewtonLimitDynamics.Polygon.ZeroForce.duration_add
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.duration_add
#check NewtonLimitDynamics.Polygon.ZeroForce.endKick_zero
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.endKick_zero
#check NewtonLimitDynamics.Polygon.ZeroForce.inertialAt_add
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.inertialAt_add
#check NewtonLimitDynamics.Polygon.ZeroForce.inertialAt_time_congr
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.inertialAt_time_congr
#check NewtonLimitDynamics.Polygon.ZeroForce.partitionMotion_append
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.partitionMotion_append
#check NewtonLimitDynamics.Polygon.ZeroForce.partitionMotion_cross_partition
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.partitionMotion_cross_partition
#check NewtonLimitDynamics.Polygon.ZeroForce.partitionMotion_cross_partition_state
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.partitionMotion_cross_partition_state
#check NewtonLimitDynamics.Polygon.ZeroForce.partitionMotion_rest
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.partitionMotion_rest
#check NewtonLimitDynamics.Polygon.ZeroForce.partitionMotion_zero_force
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.partitionMotion_zero_force
#check NewtonLimitDynamics.Polygon.ZeroForce.slow_fast_collinear_closedBoundary
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.slow_fast_collinear_closedBoundary
#check NewtonLimitDynamics.Polygon.ZeroForce.slow_fast_different_half_time
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.slow_fast_different_half_time
#check NewtonLimitDynamics.Polygon.ZeroForce.slow_fast_equal_endpoint
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.slow_fast_equal_endpoint
#check NewtonLimitDynamics.Polygon.ZeroForce.slow_two_cell_schedule
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.slow_two_cell_schedule
#check NewtonLimitDynamics.Polygon.ZeroForce.withinCell_position
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.withinCell_position
#check NewtonLimitDynamics.Polygon.ZeroForce.withinCell_position_bounded
#print axioms NewtonLimitDynamics.Polygon.ZeroForce.withinCell_position_bounded
#check NewtonLimitDynamics.Polygon.adjacent_impulseContact_iff
#print axioms NewtonLimitDynamics.Polygon.adjacent_impulseContact_iff
#check NewtonLimitDynamics.Polygon.adjacent_position_contact
#print axioms NewtonLimitDynamics.Polygon.adjacent_position_contact
#check NewtonLimitDynamics.Polygon.adjacent_velocityContact_iff
#print axioms NewtonLimitDynamics.Polygon.adjacent_velocityContact_iff
#check NewtonLimitDynamics.Polygon.all_cell_areas
#print axioms NewtonLimitDynamics.Polygon.all_cell_areas
#check NewtonLimitDynamics.Polygon.all_unsigned_cell_areas
#print axioms NewtonLimitDynamics.Polygon.all_unsigned_cell_areas
#check NewtonLimitDynamics.Polygon.central_step_area
#print axioms NewtonLimitDynamics.Polygon.central_step_area
#check NewtonLimitDynamics.Polygon.degenerate_unsigned_examples
#print axioms NewtonLimitDynamics.Polygon.degenerate_unsigned_examples
#check NewtonLimitDynamics.Polygon.det_translation
#print axioms NewtonLimitDynamics.Polygon.det_translation
#check NewtonLimitDynamics.Polygon.enclosed_gap_vanishes
#print axioms NewtonLimitDynamics.Polygon.enclosed_gap_vanishes
#check NewtonLimitDynamics.Polygon.equal_swept_area_does_not_identify_next_vertex
#print axioms NewtonLimitDynamics.Polygon.equal_swept_area_does_not_identify_next_vertex
#check NewtonLimitDynamics.Polygon.equal_time_area_reconstruction
#print axioms NewtonLimitDynamics.Polygon.equal_time_area_reconstruction
#check NewtonLimitDynamics.Polygon.extension_identity
#print axioms NewtonLimitDynamics.Polygon.extension_identity
#check NewtonLimitDynamics.Polygon.glue_first
#print axioms NewtonLimitDynamics.Polygon.glue_first
#check NewtonLimitDynamics.Polygon.glue_last
#print axioms NewtonLimitDynamics.Polygon.glue_last
#check NewtonLimitDynamics.Polygon.glue_middle_from_left
#print axioms NewtonLimitDynamics.Polygon.glue_middle_from_left
#check NewtonLimitDynamics.Polygon.glue_middle_from_right
#print axioms NewtonLimitDynamics.Polygon.glue_middle_from_right
#check NewtonLimitDynamics.Polygon.glued_position_contact
#print axioms NewtonLimitDynamics.Polygon.glued_position_contact
#check NewtonLimitDynamics.Polygon.impulseContact_position
#print axioms NewtonLimitDynamics.Polygon.impulseContact_position
#check NewtonLimitDynamics.Polygon.inward_impulses_distinct_next_vertex
#print axioms NewtonLimitDynamics.Polygon.inward_impulses_distinct_next_vertex
#check NewtonLimitDynamics.Polygon.inward_impulses_same_swept
#print axioms NewtonLimitDynamics.Polygon.inward_impulses_same_swept
#check NewtonLimitDynamics.Polygon.inward_oneCell_refinement_compatible
#print axioms NewtonLimitDynamics.Polygon.inward_oneCell_refinement_compatible
#check NewtonLimitDynamics.Polygon.inward_oneCell_refinement_defect
#print axioms NewtonLimitDynamics.Polygon.inward_oneCell_refinement_defect
#check NewtonLimitDynamics.Polygon.isum_mono
#print axioms NewtonLimitDynamics.Polygon.isum_mono
#check NewtonLimitDynamics.Polygon.isum_mul
#print axioms NewtonLimitDynamics.Polygon.isum_mul
#check NewtonLimitDynamics.Polygon.latticeMotionCell_adjacent_position_contact
#print axioms NewtonLimitDynamics.Polygon.latticeMotionCell_adjacent_position_contact
#check NewtonLimitDynamics.Polygon.latticeMotionCell_impulseContact
#print axioms NewtonLimitDynamics.Polygon.latticeMotionCell_impulseContact
#check NewtonLimitDynamics.Polygon.latticeMotionCell_zero_impulse_velocityContact
#print axioms NewtonLimitDynamics.Polygon.latticeMotionCell_zero_impulse_velocityContact
#check NewtonLimitDynamics.Polygon.lattice_step_velocity_jump
#print axioms NewtonLimitDynamics.Polygon.lattice_step_velocity_jump
#check NewtonLimitDynamics.Polygon.motion_adjacent_pair_position_contact
#print axioms NewtonLimitDynamics.Polygon.motion_adjacent_pair_position_contact
#check NewtonLimitDynamics.Polygon.motion_lattice_velocity_jump
#print axioms NewtonLimitDynamics.Polygon.motion_lattice_velocity_jump
#check NewtonLimitDynamics.Polygon.motion_restart
#print axioms NewtonLimitDynamics.Polygon.motion_restart
#check NewtonLimitDynamics.Polygon.negative_orientation_unsigned_example
#print axioms NewtonLimitDynamics.Polygon.negative_orientation_unsigned_example
#check NewtonLimitDynamics.Polygon.nsum_constant
#print axioms NewtonLimitDynamics.Polygon.nsum_constant
#check NewtonLimitDynamics.Polygon.oneCellMotionRefinementCompatible_end
#print axioms NewtonLimitDynamics.Polygon.oneCellMotionRefinementCompatible_end
#check NewtonLimitDynamics.Polygon.oneCellMotionRefinementCompatible_start
#print axioms NewtonLimitDynamics.Polygon.oneCellMotionRefinementCompatible_start
#check NewtonLimitDynamics.Polygon.parallel_identity
#print axioms NewtonLimitDynamics.Polygon.parallel_identity
#check NewtonLimitDynamics.Polygon.positive_orientation_unsigned_example
#print axioms NewtonLimitDynamics.Polygon.positive_orientation_unsigned_example
#check NewtonLimitDynamics.Polygon.positive_unsigned_area_comparison
#print axioms NewtonLimitDynamics.Polygon.positive_unsigned_area_comparison
#check NewtonLimitDynamics.Polygon.rectangle_gap_bound
#print axioms NewtonLimitDynamics.Polygon.rectangle_gap_bound
#check NewtonLimitDynamics.Polygon.refinementDefect_eq_zero_iff
#print axioms NewtonLimitDynamics.Polygon.refinementDefect_eq_zero_iff
#check NewtonLimitDynamics.Polygon.refinementStripTwice_eq_triangle
#print axioms NewtonLimitDynamics.Polygon.refinementStripTwice_eq_triangle
#check NewtonLimitDynamics.Polygon.refinementStripTwice_translation
#print axioms NewtonLimitDynamics.Polygon.refinementStripTwice_translation
#check NewtonLimitDynamics.Polygon.repeated_triangle_coverage_example
#print axioms NewtonLimitDynamics.Polygon.repeated_triangle_coverage_example
#check NewtonLimitDynamics.Polygon.restriction_cell
#print axioms NewtonLimitDynamics.Polygon.restriction_cell
#check NewtonLimitDynamics.Polygon.sector_ratio_reconstruction
#print axioms NewtonLimitDynamics.Polygon.sector_ratio_reconstruction
#check NewtonLimitDynamics.Polygon.sum_constant
#print axioms NewtonLimitDynamics.Polygon.sum_constant
#check NewtonLimitDynamics.Polygon.swept_eq
#print axioms NewtonLimitDynamics.Polygon.swept_eq
#check NewtonLimitDynamics.Polygon.telescoping
#print axioms NewtonLimitDynamics.Polygon.telescoping
#check NewtonLimitDynamics.Polygon.unsigned_block_eq
#print axioms NewtonLimitDynamics.Polygon.unsigned_block_eq
#check NewtonLimitDynamics.Polygon.unsigned_block_time_cross
#print axioms NewtonLimitDynamics.Polygon.unsigned_block_time_cross
#check NewtonLimitDynamics.Polygon.velocityContact_position
#print axioms NewtonLimitDynamics.Polygon.velocityContact_position
#check NewtonLimitDynamics.enclosure_reconstruction
#print axioms NewtonLimitDynamics.enclosure_reconstruction
#check NewtonLimitDynamics.near_and
#print axioms NewtonLimitDynamics.near_and
#check NewtonLimitDynamics.near_has_witness
#print axioms NewtonLimitDynamics.near_has_witness
#check NewtonLimitDynamics.not_near_false
#print axioms NewtonLimitDynamics.not_near_false
#check Principia1687.PropositionI.finite_componendo
#print axioms Principia1687.PropositionI.finite_componendo
#check Principia1687.PropositionI.finite_equal_areas
#print axioms Principia1687.PropositionI.finite_equal_areas
#check Principia1687.PropositionI.polygon_trajectory_defect_control
#print axioms Principia1687.PropositionI.polygon_trajectory_defect_control
#check Principia1687.constructed_quadratic_bridge
#print axioms Principia1687.constructed_quadratic_bridge
#check Principia1687.discharges_quadraticPremise_reconstruction
#print axioms Principia1687.discharges_quadraticPremise_reconstruction
#check Principia1687.lemmaX_reconstruction
#print axioms Principia1687.lemmaX_reconstruction
#check Principia1713.PropositionI.finite_componendo
#print axioms Principia1713.PropositionI.finite_componendo
#check Principia1713.PropositionI.finite_equal_areas
#print axioms Principia1713.PropositionI.finite_equal_areas
#check Principia1713.PropositionI.polygon_trajectory_defect_control
#print axioms Principia1713.PropositionI.polygon_trajectory_defect_control
#check Principia1713.corollary4_coefficient_reconstruction
#print axioms Principia1713.corollary4_coefficient_reconstruction
#check Principia1713.corollary5_coefficient_reconstruction
#print axioms Principia1713.corollary5_coefficient_reconstruction
#check Principia1713.lemmaX_reconstruction
#print axioms Principia1713.lemmaX_reconstruction
