import BarrowLib.Polygon.PointAlgebra

/-! Historical result: law_ii.
Diplomatic TEI rendering follows orig spelling; whitespace is collapsed; additions, deletions, notes and unclear readings are retained; fw forme-work is omitted.
-/

/-! 1687. Directed change of motion as an explicit mechanical premise. -/
/-! Witness: 1687.
Source: docs/m1/NATP00076.xml
SHA-256: fc2984820b61f64fdbf5efe1142ea8cf5458b75dd54fc6525f73ee705a8a9b1c
URL: https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00076#par3
Anchor URLs: NATP00076.par3 = https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00076#par3; NATP00076.par4 = https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00076#par4
Proof-step correspondence: `AdditiveImpulse` represents the explanation's addition, subtraction and oblique composition for one fixed body. The second vector is the calibrated change of velocity, with mass and impulse-to-motion proportionality supplied; this is an editorial interpretation (confidence high), not a derivation of the universal force law.
-/
/- LATIN BEGIN NATP00076.par3
Mutationem motus proportionalem esse vi motrici impressæ, & fieri secundum lineam rectam qua vis illa imprimitur.
LATIN END NATP00076.par3 -/
/- LATIN BEGIN NATP00076.par4
Si vis aliqua motum quemvis generet, dupla duplum, tripla triplum generabit, sive simul & semel, sive gradatim & successive impressa fuerit. Et hic motus quoniam in eandem semper plagam cum vi generatrice determinatur, si corpus antea movebatur, motui ejus vel conspiranti additur, vel contrario subducitur, vel obliquo oblique adjicitur, & cum eo secundum utriusq; determinationem componitur.
LATIN END NATP00076.par4 -/

namespace Principia1687.Laws
open NewtonLimitDynamics NewtonLimitDynamics.Polygon TimeSubdivision

/-- Supplied Law II interpretation for a fixed body: the second argument
already expresses the directed velocity change generated by the impulse. -/
def AdditiveImpulse (update : Point → Point → Point) : Prop :=
  ∀ u v, pointEquiv (update u v) (pointAdd u v)

end Principia1687.Laws

/-! 1713. Directed change of motion as its own mechanical premise. -/
/-! Witness: 1713.
Source: docs/m1/NATP00081.xml
SHA-256: 5c72c73d9f396d3b34475543fa7cd158ab29006fb43fa35bc63df9b7e4be6bfe
URL: https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00081#par3
Anchor URLs: NATP00081.par3 = https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00081#par3; NATP00081.par4 = https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00081#par4
Proof-step correspondence: `AdditiveImpulse` represents the explanation's addition, subtraction and oblique composition for one fixed body. The second vector is the calibrated change of velocity, with mass and impulse-to-motion proportionality supplied; this is an editorial interpretation (confidence high), not a derivation of the universal force law.
-/
/- LATIN BEGIN NATP00081.par3
Mutationem motus proportionalem esse vi motrici impressæ, & fieri secundum lineam rectam qua vis illa imprimitur.
LATIN END NATP00081.par3 -/
/- LATIN BEGIN NATP00081.par4
Si vis aliqua motum quemvis generet; dupla duplum, tripla triplum generabit, sive simul & semel, sive gradatim & successive impressa fuerit. Et hic motus (quoniam in eandem semper plagam cum vi generatrice determinatur) si corpus antea movebatur, motui ejus vel conspiranti additur, vel contrario subducitur, vel obliquo oblique adjicitur, & cum eo secundum utriusque determinationem componitur.
LATIN END NATP00081.par4 -/

namespace Principia1713.Laws
open NewtonLimitDynamics NewtonLimitDynamics.Polygon TimeSubdivision

/-- Edition-local calibrated directed-change premise. -/
def AdditiveImpulse (update : Point → Point → Point) : Prop :=
  ∀ u v, pointEquiv (update u v) (pointAdd u v)

end Principia1713.Laws
