import BarrowLib.Polygon.PointAlgebra

/-! Historical result: law_ii.
Diplomatic TEI rendering follows orig spelling; whitespace is collapsed; additions, deletions, notes and unclear readings are retained; fw forme-work is omitted.
-/

/-! NATP00090. Its own Lex 2, with the witness revisions retained. -/
/-! Witness: NATP00090.
Source: docs/m1/NATP00090.xml
SHA-256: 790b468987fd8c7716d9d43197ec3a724f7f581ec8b6ed3998edc191b951f998
URL: https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00090#par6
Anchor URLs: NATP00090.par6 = https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00090#par6
Proof-step correspondence: `CalibratedChange` supplies the difference between outgoing and incoming velocity as the directed change generated by an impulse on one fixed body. The second argument already includes the body's impulse-to-velocity calibration. This is an explicit editorial coordinate interpretation (confidence high), not a proof of the mechanical law or its proportionality constant. No parallelogram endpoint, equal area or curve-limit agreement is supplied. The printed Law II explanations are not premises of this witness.
-/
/- LATIN BEGIN NATP00090.par6
[del: Hypoth] [add: Lex] 2. [add: [del: Motum gravitum vel]] Mutationem [del: motus] [add: status movendi vel quiescendi] proportionalem esse vi impressæ et fieri secundum lineam rectam qua vis illa imprimitur.
LATIN END NATP00090.par6 -/

namespace DeMotu1684.NATP00090.Laws
open NewtonLimitDynamics NewtonLimitDynamics.Polygon TimeSubdivision

/-- Supplied directed velocity difference for a fixed body. The second
argument is the calibrated impulse, not an uncalibrated force magnitude. -/
def CalibratedChange (update : Point → Point → Point) : Prop :=
  ∀ v j, pointEquiv (pointSub (update v j) v) j

end DeMotu1684.NATP00090.Laws

/-! 1687. Directed change of motion as an explicit mechanical premise. -/
/-! Witness: 1687.
Source: docs/m1/NATP00076.xml
SHA-256: fc2984820b61f64fdbf5efe1142ea8cf5458b75dd54fc6525f73ee705a8a9b1c
URL: https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00076#par3
Anchor URLs: NATP00076.par3 = https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00076#par3; NATP00076.par4 = https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00076#par4
Proof-step correspondence: `AdditiveImpulse` represents the explanation's addition, subtraction and oblique composition for one fixed body. The second vector is the calibrated change of velocity, with mass and impulse-to-motion proportionality supplied; this is an editorial interpretation (confidence high), not a derivation of the universal force law.
-/
/- LATIN BEGIN NATP00076.par3
Mutationem motus proportionalem esse vi motrici impressæ, & fieri secundum lineam rectam qua vis illa imprimitur.
LATIN END NATP00076.par3 -/
/- LATIN BEGIN NATP00076.par4
Si vis aliqua motum quemvis generet, dupla duplum, tripla triplum generabit, sive simul & semel, sive gradatim & successive impressa fuerit. Et hic motus quoniam in eandem semper plagam cum vi generatrice determinatur, si corpus antea movebatur, motui ejus vel conspiranti additur, vel contrario subducitur, vel obliquo oblique adjicitur, & cum eo secundum utriusq; determinationem componitur.
LATIN END NATP00076.par4 -/

namespace Principia1687.Laws
open NewtonLimitDynamics NewtonLimitDynamics.Polygon TimeSubdivision

/-- Supplied Law II interpretation for a fixed body: the second argument
already expresses the directed velocity change generated by the impulse. -/
def AdditiveImpulse (update : Point → Point → Point) : Prop :=
  ∀ u v, pointEquiv (update u v) (pointAdd u v)

end Principia1687.Laws

/-! 1713. Directed change of motion as its own mechanical premise. -/
/-! Witness: 1713.
Source: docs/m1/NATP00081.xml
SHA-256: 5c72c73d9f396d3b34475543fa7cd158ab29006fb43fa35bc63df9b7e4be6bfe
URL: https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00081#par3
Anchor URLs: NATP00081.par3 = https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00081#par3; NATP00081.par4 = https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00081#par4
Proof-step correspondence: `AdditiveImpulse` represents the explanation's addition, subtraction and oblique composition for one fixed body. The second vector is the calibrated change of velocity, with mass and impulse-to-motion proportionality supplied; this is an editorial interpretation (confidence high), not a derivation of the universal force law.
-/
/- LATIN BEGIN NATP00081.par3
Mutationem motus proportionalem esse vi motrici impressæ, & fieri secundum lineam rectam qua vis illa imprimitur.
LATIN END NATP00081.par3 -/
/- LATIN BEGIN NATP00081.par4
Si vis aliqua motum quemvis generet; dupla duplum, tripla triplum generabit, sive simul & semel, sive gradatim & successive impressa fuerit. Et hic motus (quoniam in eandem semper plagam cum vi generatrice determinatur) si corpus antea movebatur, motui ejus vel conspiranti additur, vel contrario subducitur, vel obliquo oblique adjicitur, & cum eo secundum utriusque determinationem componitur.
LATIN END NATP00081.par4 -/

namespace Principia1713.Laws
open NewtonLimitDynamics NewtonLimitDynamics.Polygon TimeSubdivision

/-- Edition-local calibrated directed-change premise. -/
def AdditiveImpulse (update : Point → Point → Point) : Prop :=
  ∀ u v, pointEquiv (update u v) (pointAdd u v)

end Principia1713.Laws
