"""Inventory checked declarations and preserve their actual premise signatures.
The file-level source correspondence is a locator, not a claim of historical proof.
"""
import json
import re
from pathlib import Path
root = Path(__file__).resolve().parents[1]
correspondence = {
 'Polygon/CauchyValues.lean': ([], 'Modern explicit quotient of rational-state Cauchy names, with no historical dependency attributed. NameEquiv is eventual levelwise distance below every positive rational tolerance; reflexivity, symmetry and transitivity are proved before constructing Value. Constant embedding respects and separates state coordinate value equivalence. NameBound requires eventual distance<R+eps for every positive eps; representative invariance is proved before Within is lifted to quotient values. Symmetry, triangle, zero-radius iff equality, and convergence of constant approximants compile. Actual endpoint/time/prefix names construct values without a supplied limit point; checked levelwise and geometric-tail estimates become value bounds, and the calibrated sample endpoint value is proved distinct from its initial value by an all-level3/16 lower bound. This is realization in the explicit Cauchy quotient, not an assumed external complete coordinate space or generic completeness theorem. Quotient times/address independence, a continuous completed-time trajectory, partition independence, position-only geometry, actual intervening area and force identification remain open; Kepler area is separate.'),
 'Polygon/HarmonicBinaryPrefix.lean': (['NATP00089.par9','NATP00090.par17','NATP00077.par45','NATP00082.par51'], 'Modern construction of intermediate-time Cauchy data from actual prefixes of one global harmonic dyadic polygon family. For arbitrary binary addresses, ticks0=0 and ticks(j+1)=2*ticksj+bitj give ticksj<2^j. The actual prefix has ticksj cells of duration T/2^j and elapsed time <=T; actual coarse/fine prefix states have magnitude <=2M under T>=0 and T*(1+abs(w))<=1/2. Actual common-time refinement plus the optional extra fine cell derive adjacent error <=A/2^(j+1), A=T*M*(2*(1+abs(w))+3*T*abs(w)). Finite geometric-tail arithmetic derives arbitrary level-gap and two-sided bounds, an explicit positive-tolerance modulus and prefixName. All-zero address, zero time and exact first/two-level controls compile. No curve, limit point or Cauchy premise for the actual prefixes is supplied. Quotient point/time realization, address independence, partition independence, force identification and actual intervening-region area remain open. Source locators motivate the construction only; Kepler area is separate.'),
 'Polygon/HarmonicTimeComparison.lean': (['NATP00089.par9','NATP00090.par17','NATP00077.par45','NATP00082.par51'], 'Modern uniform time-parameter estimate for actual harmonic dyadic endpoint schedules. At the same level the cell count is identical and the two durations differ; this is not a common-time refinement. Under both nonnegative-time and named small-time premises, actual cell mismatch, prefix bounds and finite amplification give state difference <= L*abs(U-T), L=4*(1+2*abs(w))*M, at every level. The map timeName sends each admissible rational time to derived endpoint Cauchy data; delta=eps/(L+1) is positive and controls all approximants, including zero initial state. Same-time, zero-state and exact signed parameter controls compile. This proves continuity of Cauchy data only: no completed point-space realization, global-grid prefix identification, partition independence, actual polygon-trajectory region or force law is supplied or inferred. Source locators motivate the reconstruction; Kepler swept area remains separate.'),
 'Polygon/HarmonicDyadic.lean': (['NATP00089.par9','NATP00090.par17','NATP00077.par45','NATP00082.par51'], 'Modern construction of actual harmonic dyadic endpoint Cauchy data at a fixed represented rational time. Each level runs 2^j actual cells of duration T/2^j; rational value equivalence identifies the coarser schedule and exact list identity identifies the finer one, with actual elapsed time T. Under T>=0 and T*(1+abs(w))<=1/2, adjacent error is at most 3*T*(T/2^(j+1))*abs(w)*M and arbitrary finite level-gap error is at most A/2^j, A=3*T^2*abs(w)*M. Two later levels have error at most 2*A/2^N. Finite integer induction supplies an explicit positive-tolerance modulus and endpointName constructs its approximants and Cauchy proof. Zero time and exact adjacent/cap controls compile. No limit point, completeness, supplied curve, continuous time-domain trajectory, partition independence, intervening-area content or uninterrupted-force identification is assumed or inferred. The time bound has a chosen coordinate/unit calibration; Kepler swept area is separate.'),
 'Polygon/ConvexCover.lean': ([], 'Modern finite rational convex enclosure, with no claimed historical dependency. Rational interpolation uses explicitly nonnegative complementary weights; endpoint L1 bounds imply a bound for every convex interpolant. Matched patches use the same physical-time fraction on both polygon edges, then interpolate between simultaneous positions. Every patch point fits the derived coordinate square. This constructs a finite point-set enclosure; it supplies no union-area semantics, completion or trajectory.'),
 'Polygon/HarmonicCover.lean': (['NATP00089.par9','NATP00090.par17','NATP00077.par45','NATP00082.par51'], 'Modern geometric cover for actual common-time harmonic coarse/fine polygons. Under h>=0 and the named small-time condition, derived prefix state/error bounds enclose all six block corners and both matched half-cell patches in the square of radius R=h*M*(4+3*T*abs(w)) about each coarse start. One square per coarse block gives the nonnegative multiplicity-counted budget 4*n*R^2, proved equivalent to 2*T*h*M^2*(4+3*T*abs(w))^2. Both interpolation parameters are arbitrary rational unit-interval values. Exact, zero, too-small L1-ball and too-small coordinate-square controls compile. The coarse midpoint receives no impulse. This is a finite cover budget, separate from Kepler swept area; no union content, actual trajectory, continuum limit or mechanical force identification is inferred.'),
 'Polygon/TriangleBounds.lean': (['NATP00089.par9','NATP00090.par17','NATP00077.par45','NATP00082.par51'], 'Modern rational estimates for finite unsigned triangle patches in polygon comparisons. Determinant magnitude is bounded by the product of coordinate L1 magnitudes; unsigned doubled triangle magnitude is nonnegative, translation invariant and unchanged by reversing vertex order. Both incident-edge and consecutive-edge bounds are checked. Opposite signed triangles have zero signed sum and positive magnitude sum, counted with multiplicity. These finite area helpers concern the intervening-path diagnostic, distinct from Kepler areas; geometric union/enclosure, actual trajectory construction and continuum interpretation remain separate.'),
 'Polygon/HarmonicUniform.lean': (['NATP00089.par9','NATP00090.par17','NATP00077.par45','NATP00082.par51'], 'Modern mesh-uniform finite harmonic estimate derived from the actual schedules and common-denominator finite product bound. The displayed T=2*n*h is proved equivalent to both actual elapsed times. Under h>=0 and T*(1+abs(w))<=1/2, coarse/fine amplification powers are at most 2, their actual state magnitudes are at most twice the initial M, and actual state error is at most 3*T*h*abs(w)*M. The threshold uses the chosen coordinate/unit calibration. Exact boundary, zero and false unrestricted-power controls compile. No supplied curve, completion, unsigned intervening-area geometry or historical continuum/mechanical limit is inferred.'),
 'Common/FiniteGrowth.lean': ([], 'Modern elementary finite common-denominator growth arithmetic, with no claimed historical dependency. For positive D and nonnegative integer increments, P=product(D+a_j) and S=sum(a_j) satisfy P*(D-S)<=D^(length+1). If 2*S<=D, the derived rational amplification P/D^length is at most 2, including empty and zero increments. List/product/replication identities support transport to actual schedule powers. Removing smallness has a checked counterexample. No supplied trajectory, completeness, area geometry, or historical analytic theorem is inferred.'),
 'Polygon/HarmonicAccumulation.lean': (['NATP00089.par9','NATP00090.par17','NATP00077.par45','NATP00082.par51'], 'Modern finite global harmonic comparison, derived from actual cells rather than supplied stability fields. The local state defect is bounded by delta=abs(h)^2*abs(w)*(kappa+1). Coarse/fine recurrences are identified with actual n full cells and 2n half-cells having equal elapsed time. Coarse state magnitude is at most b^n times the initial magnitude; actual state error obeys the explicit nonnegative recurrence B_(n+1)=kappa^2*B_n+delta*b^n*M. Exact one/two-block errors are checked. Mesh-uniform growth, Cauchy completion, continuum trajectory, nonnegative intervening-area geometry and mechanical force identification remain open; Kepler area is separate.'),
 'Polygon/PointBounds.lean': (['NATP00089.par9','NATP00090.par17','NATP00077.par45','NATP00082.par51'], 'Modern finite coordinate L1 estimates for represented rational points and position/velocity states: nonnegativity, rational-equivalence invariance, triangle bounds and scaling. The source passages locate the polygon-to-trajectory motivation only. This diagnostic is not Euclidean area; combining position and velocity physically requires a calibration of units. No trajectory or historical norm theorem is attributed or inferred.'),
 'Polygon/HarmonicComparison.lean': (['NATP00089.par9','NATP00090.par17','NATP00077.par45','NATP00082.par51'], 'Modern finite comparison of the actual harmonic end-kick cell. Drift and kick estimates derive amplification by kappa=(1+abs(h))*(1+abs(h)*abs(w)); subtracting two actual outputs equals applying the cell to the input difference, giving a one-step perturbation bound. Signed and zero parameters are covered. No regularity assumption or stability field replaces the actual calculation. Global schedule comparison, the nonnegative region between polygons, trajectory existence and mechanical limit identification remain open.'),
 'Polygon/HarmonicRefinement.lean': (['NATP00089.par9','NATP00090.par17','NATP00077.par45','NATP00082.par51'], 'Modern finite common-time comparison of two actual cells h and one actual cell h+h of the same harmonic field and initial state. Fine position differs by -h^2*w*y and velocity by h^2*w*v+h^3*w^2*y. An explicit nonmechanical endpoint connector closes the comparison; the closed signed doubled defect reduces to triangle y,z,X and equals -h^3*w*det(x,v). Its local absolute magnitude is nonnegative. Kepler sums agree while this defect can be nonzero. Physical time/inward interpretations additionally need h>0/w>0. No global accumulation, multi-lobe region theorem, actual trajectory, convergence or force identification is proved.'),
 'DeMotu1684/AreaLaw.lean': (['NATP00089.par8','NATP00089.par9','NATP00090.par16','NATP00090.par17'], 'Separate finite De Motu Theorem 1 reconstructions, not retrospectively numbered Principia propositions. The two witnesses remain distinct at declaration level below. Named Euclidean identities and supplied area semantics give equal unsigned cell areas and derived block comparisons. The main polygon-trajectory area is separate from Kepler area; its conditional control requires a realized curve, justified nonnegative enclosure and a vanishing budget. No limiting clause or uninterrupted force is derived.'),
 'Principia1687/PropositionI.lean': (['NATP00077.par44','NATP00077.par45'], '1687-local finite Proposition I reconstruction: named Euclidean preservation identities and area semantics; unsigned equal-cell triangles and the finite componendo comparison with positive total times. Main polygon-trajectory area is not Kepler area; the conditional defect-control interface requires the actual curve and geometric enclosure separately. No 1713 premise, sector union, trajectory realization or uninterrupted-force identification is derived.'),
 'Principia1713/PropositionI.lean': (['NATP00082.par50','NATP00082.par51'], '1713-local finite Proposition I reconstruction with this edition alone: equal unsigned triangle areas and finite componendo under the named Euclidean construction premises. The main nonnegative area between polygon and trajectory has a separate conditional enclosure/budget interface. Curve existence, sector interpretation, Lemma III Corollary 4 passage and force identification remain open.'),
 'Polygon/PathDefect.lean': (['NATP00089.par9','NATP00090.par17','NATP00077.par45','NATP00082.par51'], 'Modern finite comparison of matched coarse edges and fine pairs: signed closed-boundary gap equals the difference of signed Kepler sums; absolute triangle-patch budget dominates the signed gap, has a uniform local bound, and is translation invariant. A checked two-lobe example has equal signed and unsigned Kepler sums but positive intervening patch area. These are finite polygons, not a realized trajectory. Actual polygon-trajectory area is explicitly nonnegative and geometrically enclosed in the conditional interface; enclosure and vanishing budget are supplied, not consequences of Kepler area equality.'),
 'Common/Quadratic.lean': ([], 'Logical reconstruction of eventual enclosure; all Magnitudes fields are parameters.'),
 'Common/RationalMagnitudes.lean': (['NATP00077.par26','NATP00082.par27'], 'Rational consistency model and arithmetic support, not full Euclidean geometry; triangle limit still requires a slope limit. Absolute values respect unnormalised rational equivalence, multiplication and the triangle inequality; weak-order operations permit zero factors and equivalent representations. These finite helpers support perturbation accounting, not geometric region identification, trajectory existence or a historical analytic theorem.'),
 'DeMotu1684/QuadraticDeflection.lean': (['RSreprint.H4'], 'Initial-ratio predicate only; not a proof of the manuscript hypothesis.'),
 'Principia1687/LemmaX.lean': (['NATP00077.par28'], 'Legacy conditional squeeze: supplied triangle limits and mechanical velocity-area identification.'),
 'Principia1687/ConstructedRatio.lean': (['NATP00077.par26','NATP00077.par28'], 'Constructed ratio and triangle cancellation; contact limits, mechanical enclosure and positive coefficient remain premises.'),
 'Principia1713/LemmaX.lean': (['NATP00082.par29'], 'Shared conditional geometry, not identification of edition-specific mechanical hypotheses.'),
 'Principia1713/ForceComparison.lean': (['NATP00082.par32','NATP00082.par33','NATP00082.par34'], 'Exact coefficient algebra only; common calibration, comparable force and positive denominators. Variable-force initial comparison not proved.'),
 'Polygon/Finite.lean': (['NATP00089.par9','NATP00090.par17','NATP00077.par45','NATP00082.par51'], 'Synthetic Euclidean area identities are imported; integer-coordinate instance is proved. No limiting trajectory.'),
 'Polygon/Enclosure.lean': (['NATP00077.par6','NATP00082.par7','NATP00077.par45','NATP00082.par51'], 'Rectangle arithmetic is proved. Curve enclosure, vanishing budget and inner/outer ratio limits are supplied where present in the signature.'),
 'Polygon/Contact.lean': (['NATP00089.par9','NATP00090.par17','NATP00077.par45','NATP00082.par51'], 'Modern diagnostic of the finite polygon construction: restart of the actual recurrence, endpoint contact, discrete velocity jumps, and an inward lattice nonidentification example. The passages locate the motivation only; they do not attribute this interface or its counterexample to Newton, and no continuous trajectory follows.'),
 'Polygon/RefinementStrip.lean': (['NATP00089.par9','NATP00090.par17','NATP00077.par45','NATP00082.par51'], 'Modern finite coordinate diagnostic motivated by the polygon constructions: exact Euclidean triangle area between a coarse edge and a compatible one-cell refinement. The passages locate motivation only; no limiting curve, common-force time refinement, integration, or trajectory existence is attributed or inferred.'),
 'Polygon/StripArea.lean': (['NATP00089.par9','NATP00090.par17','NATP00077.par45','NATP00082.par51'], 'Modern finite strip-area bookkeeping for the constant-force polygon (order 3). For a uniform rational cell h and constant force a, the chord of each cell is h times the incoming velocity, and the two-cell chord triangle has doubled area h cubed times det(v, a); because det(w + s a, a) = det(w, a) every such triangle has the same signed doubled area and the signed total over k triangles is k times h cubed times det(v, a). The common value may be negative; the absolute-area sum and a geometric strip decomposition remain open. Finite Fraction arithmetic only; no curve, limit or force law.'),
  'Polygon/TimeSubdivision.lean': (['NATP00089.par9','NATP00090.par17','NATP00077.par45','NATP00082.par51'], 'Modern finite coordinate diagnostic: an explicitly scheduled constant-acceleration end-kick coarse/fine comparison over positive rational durations. It proves a non-nested endpoint mismatch and closes the resulting finite boundary by a connector. The passages locate motivation only; no limiting curve, integration, trajectory existence, or Newtonian general central-force theorem is attributed or inferred.'),
 'Polygon/PartitionControl.lean': (['NATP00089.par9','NATP00090.par17','NATP00077.par45','NATP00082.par51'], 'Modern finite bookkeeping for arbitrary common-denominator end-kick schedules. The actual `partitionMotion` is the repeated `TimeSubdivision.endKick` recurrence; its exact candidate residual is `(Q/(2*D^2))*a`, with a nonnegative coefficient bounded by the maximum-cell coefficient. This is a rational-time candidate formula only: no convergence, limiting curve, integration, trajectory existence, or Newtonian general central-force theorem is attributed or inferred.'),
 'Polygon/PartialCell.lean': (['NATP00089.par9','NATP00090.par17','NATP00077.par45','NATP00082.par51'], 'Modern finite bookkeeping for a partial final end-kick cell of duration `u/D` after an actual common-denominator prefix. The partial position is the drift of the actual prefix state and equals the appended schedule `weights ++ [u]`; the exact candidate residual `((Q+u*u)/(2*D^2))*a` and the within-cell bound `Q+u*u <= M*(T+u)` for `u <= w <= M` are derived from the appended statistics. Boundaries u=0, u=w and a=0 are corollaries. Rational-time positions only: no convergence, limiting curve, integration, trajectory existence, or Newtonian general central-force theorem is attributed or inferred.'),
 'Polygon/UniformRefinement.lean': (['NATP00089.par9','NATP00090.par17','NATP00077.par45','NATP00082.par51'], 'Modern finite estimate: for each positive rational tolerance and rational time `N/E`, an explicit uniform refinement (`K = N*den+1` unit cells over `E*K`) reaches the same time with constant-force residual coefficient `Q/(2D^2)` at most the tolerance. It is one refinement per tolerance, with no sequence limit, Cauchy comparison of arbitrary partitions, Euclidean-time trajectory, or central-force theorem inferred.'),
 'Polygon/PartitionComparison.lean': (['NATP00089.par9','NATP00090.par17','NATP00077.par45','NATP00082.par51'], 'Modern finite comparison: two arbitrary common-denominator end-kick schedules reaching equivalent rational times have actual positions that agree after each is corrected by its own exact residual `(Q/(2*D^2))*a`, also at partial-cell sample times, and their actual velocities agree exactly; the candidate respects rational time equivalence. With the mesh bounds this controls partition dependence along `a`. No limit, Euclidean-time trajectory, or central-force theorem is inferred.'),
 'Polygon/Converse.lean': (['NATP00077.par48','NATP00077.par49','NATP00077.par50','NATP00082.par58','NATP00082.par59','NATP00082.par60'], 'Modern integer-coordinate reconstruction of the finite step in Proposition II Case 1 (both editions cite Law I, Euclid I.40 and Law II). Equal oriented areas Spq and SqC are equivalent to the deflection cC being parallel to Sq; with q distinct from S the step is a rational central kick. Counterexamples show that orientation, a vertex distinct from S, and the inward sense are separate premises. Case 2 finite step: inertial continuation commutes with uniform translation of the centre (motivated by the laws Cor. V, par50/par60), so equal areas about a uniformly moving centre give deflections parallel to the current radius. No realized curve, vanishing-triangle limit, or force law is treated.'),
 'Polygon/RelativeMotion.lean': (['NATP00077.par53','NATP00077.par54','NATP00082.par64','NATP00082.par65'], 'Modern integer-coordinate reconstruction of the finite step in Proposition III (both editions proceed by Corollary VI of the laws, then Law I, then Proposition II). Two bodies are advanced by one pair recursion, each taking its own deflection history. Corollary VI finite: a deflection history added to both bodies leaves both relative coordinates unchanged at every stage. Law I finite: with zero deflection the vertices of the reference body are the uniform centreAt motion of its initial pair. The deflection of the relative polygon is exactly the difference of the two deflections, which is the force composition of the proposition; equal relative oriented areas make that difference parallel to the relative radius, and with a nonzero initial relative radius they give a rational multiple of that radius at the initial step. The inward sense remains a separate premise. The moving-centre route explicitly adds the opposite of the reference deflection to both histories, identifies the reduced reference vertices at their correct times by Law I, transfers the original relative-area hypothesis, and applies the Proposition II moving-centre converse. A timing counterexample separates the true reference radius from a centre one cell earlier. Counterexamples separate the difference from the pair of absolute deflections. Finite only: no curve, limit, force law, mass, or realized-orbit area law is derived; the equal relative areas are a hypothesis.'),
 'Polygon/CentralSchedule.lean': (['NATP00077.par45','NATP00082.par51','NATP00077.par48','NATP00082.par58'], 'Modern rational reconstruction for an arbitrary position-dependent field with impulses at arrival vertices. For any central field and arbitrary unequal rational cells, areal velocity is invariant and swept doubled area equals elapsed time times it (Newton uses equal cells). For any field, one-cell refinement moves the endpoint by exactly h*k*a(y), and changes velocity by h*(a y - a X) + k*(a z - a X); a harmonic example makes both nonzero. The unequal-cell converse gives a radial impulse when areas are proportional to nonzero durations. No curve, limit, force regularity, or force identification is inferred.'),
 'Polygon/HarmonicStability.lean': (['NATP00077.par64','NATP00082.par75','NATP00077.par45','NATP00082.par51'], 'Modern rational reconstruction: for the linear central field a(p) = -w*p (compare Prop. IV Cor. 3, forces as radii for equal periods) the finite impulse construction with equal cells d conserves exactly w|x|^2 + w*d*(x.v) + |v|^2, which completes to w|x + (d/2)v|^2 + (1 - w*d^2/4)|v|^2. For w >= 0 the speed term (1 - w*d^2/4)|v_n|^2, and for a nonnegative margin the position term, stay below the initial invariant along every equal-cell schedule (mesh-uniform discrete stability). Convergence, continuous curve, and Newton general central-force theorem are not inferred.'),
 'Polygon/MonotoneEnclosure.lean': (['NATP00077.par27','NATP00077.par28','NATP00082.par28','NATP00082.par29'], 'Modern finite reconstruction of the enclosure behind Lemma X under the 1713 force clause (Vi finita, constant or continually increasing or decreasing; 1687 has vi regulari). Integer magnitudes, unit cells, start at rest: impulses between lo and hi enclose the space described between the constant-force spaces; monotone and antitone histories give the initial/final-force enclosure; a finite rising-and-falling history escapes it. No limit, continuous force, or velocity-area identification of a given curve is inferred.'),
 'Polygon/ZeroForce.lean': (['NATP00076.par1','NATP00081.par1','NATP00090.par5'], 'Modern rational coordinate reconstruction of zero impressed acceleration. The actual end-kick recurrence agrees with `p + t*v` at every finite rational schedule time, including rest, exact restart, and equivalent times across denominators. The locators motivate the inertial premise only; NATP00089.par4 is a deleted supporting witness and is not a surviving premise. No all-Euclidean-time trajectory, limiting curve, or historical proof dependency is inferred.'),
 'Polygon/InertialControl.lean': (['NATP00076.par1','NATP00081.par1','NATP00090.par5'], 'Modern rational small-time estimate for zero impressed acceleration. An explicit positive radius controls both coordinate drifts for every rational base time and an actual zero-force end-kick cell. It is a finite algebraic estimate, not an all-Euclidean-time trajectory, curve existence theorem, or historical proof dependency.'),
 'Polygon/InertialDefect.lean': (['NATP00076.par1','NATP00081.par1','NATP00090.par5'], 'Modern rational coordinate identity for zero impressed acceleration: directed determinants of samples on one inertial line compose additively, so every finite closed walk, including its explicit connector, has zero signed doubled area; four actual zero-force schedules with different partitions give a vanishing boundary. Signed sums only; no unsigned enclosure estimate, timing identification, continuum curve, or historical proof dependency is inferred.'),
 'Diagnostic/InverseCubeAreal.lean': (['NATP00077.par62','NATP00082.par73','NATP00082.par79'], 'Action diagnostic layer, not a historical proof: natural-number magnitudes of two uniform circles compared through the Proposition IV Cor. 1 proportion. An inverse-cube comparison is equivalent to equal squared areal velocity; an inverse-square instance has unequal areal velocities. The general power-law Cor. 7 is 1713 only. Supports research/action-arguments Arg002; it fixes a system-dependent action and gives no universal constant.'),
 'Diagnostic/PhaseArea.lean': (['NATP00089.par9','NATP00090.par17','NATP00077.par45','NATP00082.par51'], 'Action diagnostic layer, not a historical proof (Arg004): one-dimensional phase plane for the cell of the Proposition I construction (Law I drift, then the impulse at the arrival point), the same cell in De Motu, 1687 and 1713. For every field each step carries lines of one coordinate rigidly (Cavalieri shears); for affine fields every phase triangle keeps its doubled area at every duration; the exact energy-type invariant of the constant-force cell depends on the duration. Area preservation for nonlinear fields, limits, curves and any constant value are not inferred.'),
 'Contact/Bounds.lean': (['NATP00077.par32','NATP00077.par37','NATP00082.par37','NATP00082.par44'], 'Circle identity and positive diameter lower bound, or quadratic departure and rectangle enclosure, are explicit premises; no curved configuration is constructed.'),
 'Contact/FiniteSums.lean': (['NATP00077.par37','NATP00082.par44'], 'Finite arithmetic and modern bookkeeping of a uniform error budget. Not a historical N^-2 theorem; the geometric coefficient identification is separately checked in AreaCoefficient.lean.'),
 'Contact/AreaCoefficient.lean': (['NATP00077.par28','NATP00077.par37','NATP00082.par29','NATP00082.par44'], 'Normalized linear/parabolic coefficients and scaled constant-force example from all finite rectangle enclosures; geometric enclosure and mechanical area identification remain distinct premises.'),
 'Comparison/CircleCompare.lean': (['NATP00077.par60','NATP00082.par71','NATP00077.par31','NATP00082.par18'], 'Modern finite circular comparison for Proposition IV (1687 par60, 1713 par71). A CircleChord carries the exact finite sagitta-chord relation s times (2r minus s) equals (c over 2) squared, the intersecting-chords fact, with no limit. forceBySagitta reads centripetal force as sagitta over the square of the common time, and force_ratio_is_sagitta_ratio shows equal-time forces are proportional to the sagittae. The edition routes (1687 Prop II plus Lemma V and Lemma XI; 1713 Prop II plus Prop I Cor 2 and 4 and Lemma VII) are the limiting steps that replace the finite relation by arc squared over r, and are recorded separately as editorial interpretations, never derived and never merged.'),
  'Comparison/Routes.lean': (['NATP00082.par91','NATP00087.par89'], 'Constant-force coordinate example and matched-duration algebra; general orbit correspondence remains conditional.'),
}
declaration_correspondence = {
 'DeMotu1684.AreaLaw.natp00089_finite_equal_areas': (['NATP00089.par8','NATP00089.par9'], 'NATP00089 Theorem 1 finite equal-area reconstruction only; unresolved changing marginal hypothesis/lemma labels remain unresolved. Supplied Euclidean identities and area semantics; unsigned triangle areas counted with multiplicity. No NATP00090 or printed-edition premise.'),
 'DeMotu1684.AreaLaw.natp00090_finite_equal_areas': (['NATP00090.par16','NATP00090.par17'], 'NATP00090 Theorem 1 finite equal-area reconstruction only, with its own Law 1/Lemma 1 references. Supplied Euclidean identities and area semantics; no reconstruction of another witness revision or later limiting lemma.'),
 'DeMotu1684.AreaLaw.natp00089_finite_block_comparison': (['NATP00089.par8','NATP00089.par9'], 'Derived finite block comparison from NATP00089 equal triangles; the witness has no printed-edition componendo sentence. Positive time cell/counts are explicit. No curve, sector union, force identification or chronological resolution.'),
 'DeMotu1684.AreaLaw.natp00090_finite_block_comparison': (['NATP00090.par16','NATP00090.par17'], 'Derived finite block comparison from NATP00090 alone, before its infinitely-small-triangle clause. Positive time cell/counts and named Euclidean premises; no later-edition limit or sector interpretation.'),
 'DeMotu1684.AreaLaw.natp00089_polygon_trajectory_defect_control': (['NATP00089.par9'], 'Conditional reconstruction of the polygon-to-trajectory obligation for NATP00089: the nonnegative intervening region is NOT Kepler area. Curve existence, correct geometric enclosure and vanishing budget are supplied obligations; no historical limiting proof is completed.'),
 'DeMotu1684.AreaLaw.natp00090_polygon_trajectory_defect_control': (['NATP00090.par17'], 'Conditional NATP00090 polygon-trajectory defect control with explicitly supplied geometric enclosure and budget. It derives no curve and imports no printed-edition limiting lemma. The finite Kepler law does not imply these premises.'),
}
results=[]
for path in sorted((root/'NewtonLimitDynamics').rglob('*.lean')):
    rel=str(path.relative_to(root/'NewtonLimitDynamics'))
    sources,note=correspondence[rel]
    text=path.read_text()
    namespace=[]
    for line in text.splitlines():
        if line.startswith('namespace '): namespace.append(line.split()[1])
        if line.startswith('end ') or line == 'end': namespace.pop()
        match=re.match(r'(private )?theorem (\w+)',line)
        if match:
            local=match[2]
            header=re.search(r'(?:private )?theorem '+re.escape(local)+r'\b([\s\S]*?):=',text)
            assert header, (path,local)
            name='.'.join(namespace+[local])
            actual_sources,actual_note=declaration_correspondence.get(name,(sources,note))
            results.append({'name':name,'private':bool(match[1]),
                'file':str(path.relative_to(root)),'source_passages':actual_sources,
                'classification':'modern_reconstruction','premise_signature':header[1].strip(),
                'interpretation_and_remaining_premises':actual_note})
(root/'research/formal-results.json').write_text(json.dumps(results,ensure_ascii=False,indent=2)+'\n')
print(f'Inventoried {len(results)} theorems with signatures and source boundaries')
