"""Validate historical evidence; generate distinct proof/comparison graphs."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
schema = json.loads((root/'research/dependency-schema.yaml').read_text())
data = json.loads((root/'research/dependencies.json').read_text())
passages = {p['id']: p for p in json.loads((root/'research/passages.json').read_text())}
nodes = {n['id']: n for n in data['nodes']}
assert len(nodes) == len(data['nodes'])
for n in nodes.values():
    assert all(k in n for k in schema['required_node_fields'])
    assert n['passage'] in passages
adj = {n: [] for n in nodes}
for e in data['edges']:
    assert all(k in e for k in schema['required_edge_fields'])
    assert e['from'] in nodes and e['to'] in nodes
    assert e['passage'] in passages
    assert e['status'] in schema['statuses']
    assert e['relation'] in schema['relations']
    assert e['confidence'] in schema['confidences']
    if e['relation'] == 'proof_dependency':
        assert nodes[e['from']]['stage'] == nodes[e['to']]['stage']
        adj[e['from']].append(e['to'])
def visit(n, active, done):
    assert n not in active, 'proof cycle'
    if n in done: return
    for m in adj[n]: visit(m, active | {n}, done)
    done.add(n)
done = set()
for n in nodes: visit(n, set(), done)
text = '# M1 evidence graphs\n\nGenerated by scripts/check_graph.py. Isolated nodes mean no accepted edge, not independence.\n'
ids = list(nodes)
for stage in sorted({n['stage'] for n in nodes.values()}) + ['comparison']:
    text += '\n## '+stage+'\n\n```mermaid\nflowchart LR\n'
    for i, n in enumerate(nodes.values()):
        if stage == 'comparison' or n['stage'] == stage:
            text += f'  n{i}["{n["id"]}"]\n'
    for e in data['edges']:
        if (stage == 'comparison' and e['relation'] == 'textual_comparison') or (e['relation'] == 'proof_dependency' and nodes[e['from']]['stage'] == stage):
            text += f'  n{ids.index(e["from"])} -->|{e["status"]}| n{ids.index(e["to"])}\n'
    text += '```\n'
(root/'research/graphs.md').write_text(text)
print(f'Validated {len(nodes)} nodes and {len(data["edges"])} edges')
