"""Validate evidence and emit separate proof, proposal and comparison graphs.

This checks local anchors and source transcription identity, not live URL uptime,
manuscript palaeography, or the truth of a claimed historical dependency.
"""
import json
from pathlib import Path
import xml.etree.ElementTree as ET
from catalogue_m1 import render, NS

root = Path(__file__).resolve().parents[1]
schema = json.loads((root/'research/dependency-schema.yaml').read_text())
data = json.loads((root/'research/dependencies.json').read_text())
records = json.loads((root/'research/passages.json').read_text())
passages = {p['id']: p for p in records}
assert len(passages) == len(records), 'duplicate passage'
nodes = {n['id']: n for n in data['nodes']}
assert len(nodes) == len(data['nodes']), 'duplicate node'
xmls = {}
for p in records:
    assert all(k in p for k in schema['required_passage_fields']), p['id']
    path = root/p['source_path']
    assert path.is_file(), path
    assert p['url'].startswith('https://'), p['id']
    assert path.with_suffix('.md').is_file(), f'no source companion: {path}'
    if path.suffix == '.xml':
        if path not in xmls:
            xmls[path] = {e.get(NS+'id'): e for e in ET.parse(path).iter() if e.get(NS+'id')}
        assert p['anchor'] in xmls[path], p['id']
        e = xmls[path][p['anchor']]
        assert p['latin'] == ' '.join(render(e).split()), f'stale passage: {p["id"]}'
        assert p['tei'] == ET.tostring(e, encoding='unicode'), f'stale TEI: {p["id"]}'
        assert p['url'].endswith('#'+p['anchor']), p['id']
for n in nodes.values():
    assert all(k in n for k in schema['required_node_fields']), n['id']
    assert n['passage'] in passages, n['id']
    assert n['stage'] == passages[n['passage']]['stage'], n['id']
    if n['stage'] == 'proposed1694':
        assert 'manuscript_identity' in n and 'proposed_number' in n, n['id']
adj = {n: [] for n in nodes}
proposed = {n: [] for n in nodes}
seen = set()
for e in data['edges']:
    assert all(k in e for k in schema['required_edge_fields']), e
    assert e['from'] in nodes and e['to'] in nodes
    assert e['passage'] in passages
    assert e['status'] in schema['statuses']
    assert e['relation'] in schema['relations']
    assert e['confidence'] in schema['confidences']
    p = passages[e['passage']]
    for key in ['witness', 'url', 'revision_layer']:
        assert e[key] == p[key], f'stale edge {key}: {e}'
    assert e['source_stage'] == p['stage'], e
    key = (e['from'], e['to'], e['relation'], e['passage'])
    assert key not in seen, 'duplicate edge'
    seen.add(key)
    if e['relation'] == 'proof_dependency':
        assert e['status'] in ['explicit_dependency', 'implicit_dependency'], e
        assert nodes[e['from']]['stage'] == nodes[e['to']]['stage'] == p['stage'], e
        assert p['stage'] != 'proposed1694', e
        adj[e['from']].append(e['to'])
    if e['relation'] in ['proposed_dependency', 'proposed_reordering']:
        assert nodes[e['from']]['stage'] == nodes[e['to']]['stage'] == 'proposed1694', e
        proposed[e['from']].append(e['to'])
def acyclic(graph):
    def visit(n, active, done):
        assert n not in active, f'cycle at {n}'
        if n in done:
            return
        for m in graph[n]:
            visit(m, active | {n}, done)
        done.add(n)
    done = set()
    for n in graph:
        visit(n, set(), done)
acyclic(adj)
acyclic(proposed)
text = '# Evidence graphs\n\nGenerated by scripts/check_graph.py. Isolated nodes mean no accepted edge, not independence. Proposed edges are not accepted proof dependencies.\n'
ids = list(nodes)
for stage in sorted({n['stage'] for n in nodes.values()}) + ['comparison']:
    text += '\n## '+stage+'\n\n```mermaid\nflowchart LR\n'
    for i, n in enumerate(nodes.values()):
        if stage == 'comparison' or n['stage'] == stage:
            text += f'  n{i}["{n["id"]}"]\n'
    for e in data['edges']:
        include = ((stage == 'comparison' and e['relation'] == 'textual_comparison') or
                   (stage != 'comparison' and nodes[e['from']]['stage'] == stage and
                    e['relation'] in ['proof_dependency', 'proposed_dependency', 'proposed_reordering']))
        if include:
            arrow = '-->' if e['relation'] == 'proof_dependency' else '-.->'
            label = e['relation'] if e['relation'].startswith('proposed') else e['status']
            text += f'  n{ids.index(e["from"])} {arrow}|{label}| n{ids.index(e["to"])}\n'
    text += '```\n'
(root/'research/graphs.md').write_text(text)
# Emit references for actual Lean elaboration, rather than checking name strings.
ledger = json.loads((root/'research/formal-results.json').read_text())
for result in ledger:
    assert (root/result['file']).is_file(), result['name']
    assert all(p in passages for p in result['source_passages']), result['name']

refs = sorted({ref for p in records for ref in p['formal_refs']} |
              {ref for e in data['edges'] for ref in e['formal_refs']} |
              {r['name'] for r in ledger if not r['private']})
check = 'import NewtonLimitDynamics\n\n-- Generated; compile with lake env lean research/CheckReferences.lean.\n'
check += ''.join(f'#check {r}\n#print axioms {r}\n' for r in refs)
(root/'research/CheckReferences.lean').write_text(check)
print(f'Validated {len(nodes)} nodes, {len(data["edges"])} edges, {len(records)} passages; {len(refs)} Lean references emitted')
