import ModernLib.Polygon.Converse

/-!
Finite relative-motion step for Proposition III (1687 NATP00077 par53–54,
1713 NATP00082 par64–65).  Both editions prove the proposition the same way:
the laws' Corollary VI adds an equal and contrary parallel acceleration to both
bodies, Law I fixes the resulting motion of the reference body, and
Proposition II then identifies the remaining force as centripetal.

The reconstruction is the finite integer-coordinate polygon of
`Polygon.Finite`, now for **two** bodies in one pair recursion.  Each body
continues inertially and then takes its own deflection for the cell.  Three
results mirror the three steps of Newton's proof:

* `corVI_relative`: a deflection history added to *both* bodies changes
  neither relative coordinate, at any stage (Corollary VI);
* `lawI_uniform`: with no deflection the reference body's vertices are the
  uniform motion `Converse.centreAt` of its initial pair (Law I);
* `relative_equal_area_central`: equal relative oriented areas make the
  *difference* of the two deflections parallel to the relative radius
  (Proposition II applied to the relative polygon).

`relative_deflection_difference` is the compositional content of the
proposition's statement: the relative polygon's deflection in each cell is the
difference of the two bodies' deflections, i.e. the force toward the other body
composed with the whole accelerative force of the other body.

Finite only.  No curve, no limit, no force law and no mass is produced; the
"force" of a cell is its deflection vector.  The equal relative areas are a
supplied hypothesis, not a consequence of a realized orbit, and the reference
body's own force history is arbitrary.
-/

namespace NewtonLimitDynamics.Polygon.RelativeMotion

open NewtonLimitDynamics.Polygon
open NewtonLimitDynamics.Polygon.Converse (sub centreAt)

def add (x y : LatticePoint) : LatticePoint := (x.1 + y.1, x.2 + y.2)

-- Modern dependency score: 0 (M=0, H=0; transitive project theorems/axioms).
theorem add_zero_right (a : LatticePoint) : add a (0, 0) = a := by
  simp [add]

/-- A summand common to both sides cancels in a difference. -/
-- Modern dependency score: 0 (M=0, H=0; transitive project theorems/axioms).
theorem add_common_cancel (a b c : LatticePoint) : sub (add a c) (add b c) = sub a b := by
  simp only [add, sub]
  apply Prod.ext <;> dsimp <;> omega

-- Modern dependency score: 0 (M=0, H=0; transitive project theorems/axioms).
theorem add_sub_distrib (a b c d : LatticePoint) :
    sub (add a b) (add c d) = add (sub a c) (sub b d) := by
  simp only [add, sub]
  apply Prod.ext <;> dsimp <;> omega

/-- Inertial continuation commutes with taking the difference of two pairs. -/
-- Modern dependency score: 0 (M=0, H=0; transitive project theorems/axioms).
theorem extend_sub (a b c d : LatticePoint) :
    sub (extend a b) (extend c d) = extend (sub a c) (sub b d) := by
  simp only [sub, extend]
  apply Prod.ext <;> dsimp <;> omega

-- Modern dependency score: 0 (M=0, H=0; transitive project theorems/axioms).
theorem det_add (q x y : LatticePoint) : det q (add x y) = det q x + det q y := by
  simp only [det, add, Int.mul_add]
  omega

/-- Two bodies at one stage: the first body occupies the consecutive vertices
    `p, q`, the reference body occupies `s, t`. -/
structure PairState where
  p : LatticePoint
  q : LatticePoint
  s : LatticePoint
  t : LatticePoint

/-- Two-body vertex sequence, one pair recursion.  `d` is the first body's
    deflection history and `e` the reference body's.  In cell `n` each body
    continues inertially from its current pair and then takes that cell's
    deflection at the arrival vertex. -/
def pairMotion (z : PairState) (d e : Nat → LatticePoint) : Nat → PairState
  | 0 => z
  | n+1 =>
    let o := pairMotion z d e n
    { p := o.q,
      q := add (extend o.p o.q) (d n),
      s := o.t,
      t := add (extend o.s o.t) (e n) }

/-- Relative coordinates of the first body with respect to the reference
    body. -/
def relP (z : PairState) : LatticePoint := sub z.p z.s

def relQ (z : PairState) : LatticePoint := sub z.q z.t

def relPAt (z : PairState) (d e : Nat → LatticePoint) (n : Nat) : LatticePoint :=
  relP (pairMotion z d e n)

def relQAt (z : PairState) (d e : Nat → LatticePoint) (n : Nat) : LatticePoint :=
  relQ (pairMotion z d e n)

-- Modern dependency score: 0 (M=0, H=0; transitive project theorems/axioms).
theorem relP_succ (z : PairState) (d e : Nat → LatticePoint) (n : Nat) :
    relPAt z d e (n + 1) = relQAt z d e n :=
  rfl

/-- The relative polygon's step: inertial continuation of the relative pair plus
    the **difference** of the two deflections.  This is the finite content of
    Proposition III's force composition (1687 par53, 1713 par64): the relative
    motion is generated by the force toward the other body together with the
    whole accelerative force of the other body, taken with the contrary
    sense. -/
-- Modern dependency score: 2/2 (M=2, H=0; transitive project theorems/axioms).
theorem relative_deflection_difference (z : PairState) (d e : Nat → LatticePoint) (n : Nat) :
    relQAt z d e (n + 1) =
      add (extend (relPAt z d e n) (relQAt z d e n)) (sub (d n) (e n)) := by
  simp only [pairMotion, relPAt, relQAt, relP, relQ, add_sub_distrib, extend_sub]

/-- A body's own deflection is exactly the gap between its next vertex and the
    inertial continuation of its current pair. -/
-- Modern dependency score: 0 (M=0, H=0; transitive project theorems/axioms).
theorem absolute_deflection (z : PairState) (d e : Nat → LatticePoint) (n : Nat) :
    sub (pairMotion z d e (n + 1)).q (extend (pairMotion z d e n).p (pairMotion z d e n).q) =
      d n := by
  simp only [pairMotion, sub, add]
  apply Prod.ext <;> dsimp <;> omega

/-- The laws' Corollary VI, finite form (1687 par54, 1713 par65): a deflection
    history added to **both** bodies leaves both relative coordinates unchanged
    at every stage.  The common history is arbitrary, so this is the polygon
    form of "equal accelerative forces along parallel lines". -/
-- Modern dependency score: 5/5 (M=5, H=0; transitive project theorems/axioms).
theorem corVI_relative (z : PairState) (d e h : Nat → LatticePoint) (n : Nat) :
    relPAt z (fun i => add (d i) (h i)) (fun i => add (e i) (h i)) n = relPAt z d e n ∧
      relQAt z (fun i => add (d i) (h i)) (fun i => add (e i) (h i)) n = relQAt z d e n := by
  induction n with
  | zero => exact ⟨rfl, rfl⟩
  | succ n ih =>
    refine ⟨?_, ?_⟩
    · rw [relP_succ, relP_succ, ih.2]
    · rw [relative_deflection_difference, relative_deflection_difference, ih.1, ih.2]
      simp only [add_common_cancel]

/-- Corollary VI is not vacuous: a nonzero common history really does change
    both bodies' absolute deflections while `corVI_relative` keeps the relative
    polygon fixed.  First cell of an explicit pair state. -/
def exampleState : PairState := { p := (0, 0), q := (2, 0), s := (0, 3), t := (2, 3) }

-- Modern dependency score: 0 (M=0, H=0; transitive project theorems/axioms).
theorem common_deflection_example :
    (relQAt exampleState (fun _ => (0, -2)) (fun _ => (0, 0)) 1 =
        relQAt exampleState (fun _ => (0, -1)) (fun _ => (0, 1)) 1) ∧
      (fun _ => (0, -2)) 0 ≠ (fun _ => (0, -1)) 0 ∧
      sub ((fun _ => (0, -2)) 0) ((fun _ => (0, 0)) 0) =
        sub ((fun _ => (0, -1)) 0) ((fun _ => (0, 1)) 0) := by
  decide

/-- Law I, finite form (cited in 1687 par54, 1713 par65): with no deflection the
    reference body's vertices are the uniform motion `centreAt` of its initial
    pair.  The first body's deflections are irrelevant to this claim. -/
-- Modern dependency score: 1/1 (M=1, H=0; transitive project theorems/axioms).
theorem lawI_uniform (z : PairState) (d e : Nat → LatticePoint) (he : ∀ i, e i = (0, 0))
    (n : Nat) :
    (pairMotion z d e n).s = centreAt z.s (sub z.t z.s) n ∧
      (pairMotion z d e n).t = centreAt z.s (sub z.t z.s) (n + 1) := by
  induction n with
  | zero =>
    refine ⟨?_, ?_⟩
    · simp only [pairMotion, centreAt]
      apply Prod.ext <;> dsimp <;> omega
    · simp only [pairMotion, centreAt, sub]
      apply Prod.ext <;> dsimp <;> omega
  | succ n ih =>
    refine ⟨?_, ?_⟩
    · rw [show (pairMotion z d e (n + 1)).s = (pairMotion z d e n).t from rfl]
      exact ih.2
    · rw [show (pairMotion z d e (n + 1)).t =
          add (extend (pairMotion z d e n).s (pairMotion z d e n).t) (e n) from rfl]
      rw [he n, add_zero_right, ih.1, ih.2]
      simp only [extend, centreAt, sub]
      apply Prod.ext <;> dsimp <;> simp only [Int.ofNat_add, Int.add_mul] <;> omega

/-- With an inertial reference body, the relative radius from the uniform
    `centreAt` is the relative coordinate of the constructed polygon: Newton's
    moving centre is the reference body itself. -/
-- Modern dependency score: 2/2 (M=2, H=0; transitive project theorems/axioms).
theorem centre_is_reference_body (z : PairState) (d e : Nat → LatticePoint)
    (he : ∀ i, e i = (0, 0)) (n : Nat) :
    sub (pairMotion z d e n).q (centreAt z.s (sub z.t z.s) (n + 1)) = relQAt z d e n := by
  rw [← (lawI_uniform z d e he n).2, relQAt, relQ]

/-- Newton's route for Proposition III: Corollary VI reduces to the uniformly
    moving reference body, Law I makes that body the `centreAt` motion, and the
    moving-centre converse of Proposition II (`Converse`) then makes the
    deflection from the inertial continuation parallel to the relative
    radius. -/
-- Modern dependency score: 15/16 (M=15, H=1; transitive project theorems/axioms).
theorem propIII_via_moving_centre (z : PairState) (d e : Nat → LatticePoint)
    (h : ∀ n, det (relQAt z d e n) (relQAt z d e (n + 1)) =
      det (relPAt z d e n) (relQAt z d e n)) (n : Nat) :
    det (relQAt z d e n) (sub (d n) (e n)) = 0 := by
  -- Corollary VI: cancel the reference body's deflection in both histories.
  let d' := fun i => add (d i) (sub (0, 0) (e i))
  let e' := fun i => add (e i) (sub (0, 0) (e i))
  have he' : ∀ i, e' i = (0, 0) := by
    intro i
    apply Prod.ext <;> dsimp [e', add, sub] <;> omega
  have hdiff : ∀ i, d' i = sub (d i) (e i) := by
    intro i
    apply Prod.ext <;> dsimp [d', add, sub] <;> omega
  have hrelative := corVI_relative z d e (fun i => sub (0, 0) (e i))
  -- Law I identifies .p with time i and .q with time i+1.
  have hp (i : Nat) :
      sub (pairMotion z d' e' i).p (centreAt z.s (sub z.t z.s) i) =
        relPAt z d e i := by
    rw [← (lawI_uniform z d' e' he' i).1]
    exact (hrelative i).1
  have hq (i : Nat) :
      sub (pairMotion z d' e' i).q (centreAt z.s (sub z.t z.s) (i + 1)) =
        relQAt z d e i :=
    (centre_is_reference_body z d' e' he' i).trans (hrelative i).2
  -- Proposition II applies to the reduced body's .p vertex sequence.
  have hareas : ∀ i,
      det (sub (pairMotion z d' e' (i + 1)).p (centreAt z.s (sub z.t z.s) (i + 1)))
        (sub (pairMotion z d' e' (i + 2)).p (centreAt z.s (sub z.t z.s) (i + 2))) =
      det (sub (pairMotion z d' e' i).p (centreAt z.s (sub z.t z.s) i))
        (sub (pairMotion z d' e' (i + 1)).p (centreAt z.s (sub z.t z.s) (i + 1))) := by
    intro i
    simpa only [hp, relP_succ] using h i
  have hc := Converse.moving_centre_equal_areas_central z.s (sub z.t z.s)
    (fun i => (pairMotion z d' e' i).p) hareas n
  change det (sub (pairMotion z d' e' n).q (centreAt z.s (sub z.t z.s) (n + 1)))
    (sub (pairMotion z d' e' (n + 1)).q
      (extend (pairMotion z d' e' n).p (pairMotion z d' e' n).q)) = 0 at hc
  rw [hq, absolute_deflection, hdiff] at hc
  exact hc

/-- Regression for the moving-centre indexing: three consecutive true relative
    radii have equal oriented areas, while pairing .q with time n instead of
    n+1 gives unequal areas, even with an inertial reference body. -/
-- Modern dependency score: 0 (M=0, H=0; transitive project theorems/axioms).
theorem moving_centre_alignment_example :
    let z : PairState := { p := (0, -1), q := (2, 0), s := (0, 0), t := (1, 0) }
    let d : Nat → LatticePoint := fun n => if n = 0 then (-2, 0) else (0, -2)
    let e : Nat → LatticePoint := fun _ => (0, 0)
    det (relQAt z d e 0) (relQAt z d e 1) =
      det (relQAt z d e 1) (relQAt z d e 2) ∧
    det (sub (pairMotion z d e 0).q (centreAt z.s (sub z.t z.s) 0))
        (sub (pairMotion z d e 1).q (centreAt z.s (sub z.t z.s) 1)) ≠
      det (sub (pairMotion z d e 1).q (centreAt z.s (sub z.t z.s) 1))
        (sub (pairMotion z d e 2).q (centreAt z.s (sub z.t z.s) 2)) := by
  decide

/-- Proposition III, finite step in relative coordinates: equal relative
    oriented areas in equal cells make the difference of the two deflections
    parallel to the relative radius. -/
-- Modern dependency score: 4/5 (M=4, H=1; transitive project theorems/axioms).
theorem relative_equal_area_central (z : PairState) (d e : Nat → LatticePoint)
    (h : ∀ n, det (relQAt z d e n) (relQAt z d e (n + 1)) =
      det (relPAt z d e n) (relQAt z d e n)) (n : Nat) :
    det (relQAt z d e n) (sub (d n) (e n)) = 0 := by
  have hn := h n
  rw [relative_deflection_difference, det_add, extension_identity] at hn
  omega

/-- With a nonzero relative radius the same step gives an explicit rational
    multiple `a/b` of that radius. The inward sense is a separate premise. -/
-- Modern dependency score: 6/7 (M=6, H=1; transitive project theorems/axioms).
theorem relative_rational_central (z : PairState) (d e : Nat → LatticePoint)
    (h : ∀ n, det (relQAt z d e n) (relQAt z d e (n + 1)) =
      det (relPAt z d e n) (relQAt z d e n))
    (hq : relQAt z d e 0 ≠ (0, 0)) :
    ∃ a b : Int, b ≠ 0 ∧ b * (sub (d 0) (e 0)).1 = a * (relQAt z d e 0).1 ∧
      b * (sub (d 0) (e 0)).2 = a * (relQAt z d e 0).2 :=
  Converse.parallel_is_multiple (relQAt z d e 0) (sub (d 0) (e 0)) hq
    (relative_equal_area_central z d e h 0)

/-- The parallelism is a statement about the **difference**: two different pairs
    of absolute deflection histories with the same difference give the same
    relative conclusion.  Concrete first cell. -/
-- Modern dependency score: 0 (M=0, H=0; transitive project theorems/axioms).
theorem difference_not_pair_example :
    sub ((fun _ : Nat => (0, -2)) 0) ((fun _ : Nat => (0, 0)) 0) =
      sub ((fun _ : Nat => (1, -1)) 0) ((fun _ : Nat => (1, 1)) 0) ∧
    ((fun _ : Nat => (0, -2)) 0, (fun _ : Nat => (0, 0)) 0) ≠
      ((fun _ : Nat => (1, -1)) 0, (fun _ : Nat => (1, 1)) 0) := by
  decide

end NewtonLimitDynamics.Polygon.RelativeMotion
