import BarrowLib.Common.UltimateScaling
import NewtonLimitDynamics.Historical.LemmaX

/-! Historical result: lemma_x_corollary_i.
Diplomatic TEI rendering follows orig spelling; whitespace is collapsed; additions, deletions, notes and unclear readings are retained; fw forme-work is omitted.
Each edition retains its exact source statement.
-/

/-! 1687. Equal forces: errors at proportional times share one Lemma X coefficient. -/
/-! Witness: 1687.
Source: docs/m1/NATP00077.xml
SHA-256: 57a8eb4ae7307faed09e2ae572a4975ea2011e679ce52e6ad2413028c424dffa
URL: https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00077#par29
Anchor URLs: NATP00077.par29 = https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00077#par29
Proof-step correspondence: Each error is a function of its own vanishing time. Equal forces similarly applied are represented by one Lemma X coefficient `c` for both errors, a supplied premise; the similar figures enter only through it and through the fixed time proportion `r`. The edition's Lemma X reconstruction gives each error divided by the square of its time the ultimate value `c`, with the second error read at the proportional time `r * t`. For positive `c`, two normalized errors with one ultimate value express "ut quadrata temporum ... quam proxime"; the ultimate ratio of the two errors themselves is not formed. The places reached without the forces and the similarity of the figures are not constructed.
Historical dependency ledger for this exact witness:
- P1687.L10 → P1687.L10C1; passage NATP00077.par29 ("Et hinc facile colligitur"); witness De Motu Corporum (Liber Primus) (1687); URL https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00077#par29; status explicit_dependency; confidence high.
-/
/- LATIN BEGIN NATP00077.par29
Corol. 1. Et hinc facile colligitur, quod corporum similes similium figurarum partes temporibus proportionalibus describentium errores, qui viribus æqualibus in partibus istis ad corpora similiter applicatis generantur, & mensurantur a locis figurarum, ad quæ corpora temporibus ijsdem proportionalibus absq; viribus istis pervenirent, sunt ut quadrata temporum in quibus generantur quam proxime.
LATIN END NATP00077.par29 -/

namespace Principia1687.LemmaX
open NewtonLimitDynamics NewtonLimitDynamics.Fraction

/-- Errors generated by equal forces, sharing the positive Lemma X coefficient
`c`, are ultimately as the squares of their times when the second body's time
is the fixed multiple `r` of the first's. The shared `c` is the supplied
reading of "viribus æqualibus ... similiter applicatis". -/
theorem corollary1_errors_as_squares_of_times (e₁ e₂ : Fraction → Fraction)
    (c r : Fraction) (hc : positive c) (hr : positive r)
    (p₁ : Principia1687.LemmaXPremises magnitudes (ratio e₁) c)
    (p₂ : Principia1687.LemmaXPremises magnitudes (ratio e₂) c) :
    QuadraticInitialDeflection magnitudes (ratio e₁) c ∧
      QuadraticInitialDeflection magnitudes (fun t => ratio e₂ (mul r t)) c :=
  ⟨⟨hc, Principia1687.lemmaX_reconstruction _ _ _ p₁⟩,
    ⟨hc, ultimate_time_scale r hr (Principia1687.lemmaX_reconstruction _ _ _ p₂)⟩⟩

end Principia1687.LemmaX

/-! 1713. Equal forces: errors at proportional times share one Lemma X coefficient. -/
/-! Witness: 1713.
Source: docs/m1/NATP00082.xml
SHA-256: 4a288b47da21c70b46f02e74092c8c16b3f1e7d301a2f04169439a767b949d0c
URL: https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00082#par30
Anchor URLs: NATP00082.par30 = https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00082#par30
Proof-step correspondence: Each error is a function of its own vanishing time, measured from the place reached without the forces ("per distantias corporum"). Equal forces of any kind similarly applied are represented by one Lemma X coefficient `c` for both errors, a supplied premise; the similar figures enter only through it and through the fixed time proportion `r`. The edition's Lemma X reconstruction gives each error divided by the square of its time the positive ultimate value `c`, with the second error read at the proportional time `r * t`. The ultimate ratio of the two errors themselves is not formed, and the places and figures are not constructed. The TEI reading "corporium" is retained.
Historical dependency ledger for this exact witness:
- P1713.L10 → P1713.L10C1; passage NATP00082.par30 ("Et hinc facile colligitur"); witness De Motu Corporum (Liber Primus) (1713); URL https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00082#par30; status explicit_dependency; confidence high.
-/
/- LATIN BEGIN NATP00082.par30
Corol. 1. Et hinc facile colligitur, quod corporum similes similium Figurarum partes temporibus proportionalibus describentium Errores, qui viribus quibusvis æqualibus in partibus ad corpora similiter applicatis generantur, & mensurantur per distantias corporium a Figurarum similium locis illis ad quæ corpora eadem temporibus iisdem proportionalibus absq; viribus istis pervenirent, sunt ut quadrata temporum in quibus generantur quam proxime.
LATIN END NATP00082.par30 -/

namespace Principia1713.LemmaX
open NewtonLimitDynamics NewtonLimitDynamics.Fraction

/-- The 1713 statement from this edition's Lemma X premises. The shared positive
`c` is the supplied reading of "viribus quibusvis æqualibus ... similiter
applicatis". -/
theorem corollary1_errors_as_squares_of_times (e₁ e₂ : Fraction → Fraction)
    (c r : Fraction) (hc : positive c) (hr : positive r)
    (p₁ : Principia1713.LemmaXPremises magnitudes (ratio e₁) c)
    (p₂ : Principia1713.LemmaXPremises magnitudes (ratio e₂) c) :
    QuadraticInitialDeflection magnitudes (ratio e₁) c ∧
      QuadraticInitialDeflection magnitudes (fun t => ratio e₂ (mul r t)) c :=
  ⟨⟨hc, Principia1713.lemmaX_reconstruction _ _ _ p₁⟩,
    ⟨hc, ultimate_time_scale r hr (Principia1713.lemmaX_reconstruction _ _ _ p₂)⟩⟩

end Principia1713.LemmaX
