import BarrowLib.Common.UltimateScaling
import NewtonLimitDynamics.Historical.LemmaX

/-! Historical result: lemma_x_corollary_ii.
Diplomatic TEI rendering follows orig spelling; whitespace is collapsed; additions, deletions, notes and unclear readings are retained; fw forme-work is omitted.
Each edition retains its exact source statement.
-/

/-! 1687. Proportional forces: errors as forces and squares of times jointly. -/
/-! Witness: 1687.
Source: docs/m1/NATP00077.xml
SHA-256: 57a8eb4ae7307faed09e2ae572a4975ea2011e679ce52e6ad2413028c424dffa
URL: https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00077#par30
Anchor URLs: NATP00077.par30 = https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00077#par30
Proof-step correspondence: A force `f` similarly applied is represented by the Lemma X coefficient `k * f`, with one calibration `k` for all the forces compared. This supplied premise is the reading of Law II's proportionality of generated motion to force; the project's Law II predicate does not produce it. The edition's Lemma X reconstruction then makes each error divided by its force and the square of its time ultimately the positive calibration `k`; for two bodies the second error is read at the proportional time `r * t`. One common ultimate value expresses "ut vires & quadrata temporum conjunctim". The ultimate ratio of the two errors themselves is not formed.
Historical dependency ledger for this exact witness:
- P1687.L10 → P1687.L10C2; passage NATP00077.par30 (errors generated as in Lemma X); witness De Motu Corporum (Liber Primus) (1687); URL https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00077#par30; status implicit_dependency; confidence medium.
- P1687.L10C1 → P1687.L10C2; passage NATP00077.par30 ("Errores autem" continues Corollary 1's errors); witness De Motu Corporum (Liber Primus) (1687); URL https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00077#par30; status implicit_dependency; confidence medium.
- P1687.Law2 → P1687.L10C2; passage NATP00077.par30 (errors proportional to the forces); witness De Motu Corporum (Liber Primus) (1687); URL https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00077#par30; status editorial_interpretation; confidence medium.
-/
/- LATIN BEGIN NATP00077.par30
Corol. 2. Errores autem qui viribus proportionalibus similiter applicatis generantur, sunt ut vires & quadrata temporum conjunctim.
LATIN END NATP00077.par30 -/

namespace Principia1687.LemmaX
open NewtonLimitDynamics NewtonLimitDynamics.Fraction

/-- An error generated by the force `f`, with Lemma X coefficient `k * f`,
divided by the force and the square of its time, is ultimately the positive
calibration `k`. The coefficient `k * f` is the supplied reading of the
proportional forces. -/
theorem corollary2_error_normalized (e : Fraction → Fraction) (k f : Fraction)
    (hk : positive k) (hf : positive f)
    (p : Principia1687.LemmaXPremises magnitudes (ratio e) (mul k f)) :
    QuadraticInitialDeflection magnitudes (fun t => quotient (ratio e t) f hf) k :=
  ⟨hk, ultimate_target_congr
    (ultimate_quotient f hf (Principia1687.lemmaX_reconstruction _ _ _ p))
    (by unfold equiv quotient mul; dsimp only; ac_rfl)⟩

/-- Two errors generated by proportional forces at proportional times share
the positive ultimate value `k` after division by force and squared time. -/
theorem corollary2_errors_jointly (e₁ e₂ : Fraction → Fraction) (k f₁ f₂ r : Fraction)
    (hk : positive k) (hf₁ : positive f₁) (hf₂ : positive f₂) (hr : positive r)
    (p₁ : Principia1687.LemmaXPremises magnitudes (ratio e₁) (mul k f₁))
    (p₂ : Principia1687.LemmaXPremises magnitudes (ratio e₂) (mul k f₂)) :
    QuadraticInitialDeflection magnitudes (fun t => quotient (ratio e₁ t) f₁ hf₁) k ∧
      QuadraticInitialDeflection magnitudes
        (fun t => quotient (ratio e₂ (mul r t)) f₂ hf₂) k :=
  ⟨corollary2_error_normalized e₁ k f₁ hk hf₁ p₁,
    ⟨hk, ultimate_time_scale r hr (corollary2_error_normalized e₂ k f₂ hk hf₂ p₂).2⟩⟩

end Principia1687.LemmaX

/-! 1713. Proportional forces: errors as forces and squares of times jointly. -/
/-! Witness: 1713.
Source: docs/m1/NATP00082.xml
SHA-256: 4a288b47da21c70b46f02e74092c8c16b3f1e7d301a2f04169439a767b949d0c
URL: https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00082#par31
Anchor URLs: NATP00082.par31 = https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00082#par31
Proof-step correspondence: A force `f` similarly applied to similar parts of similar figures is represented by the Lemma X coefficient `k * f`, with one calibration `k` for all the forces compared. This supplied premise is the reading of Law II's proportionality of generated motion to force; the project's Law II predicate does not produce it. The edition's Lemma X reconstruction then makes each error divided by its force and the square of its time ultimately the positive calibration `k`; for two bodies the second error is read at the proportional time `r * t`. The ultimate ratio of the two errors themselves is not formed.
Historical dependency ledger for this exact witness:
- P1713.L10 → P1713.L10C2; passage NATP00082.par31 (errors generated as in Lemma X); witness De Motu Corporum (Liber Primus) (1713); URL https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00082#par31; status implicit_dependency; confidence medium.
- P1713.L10C1 → P1713.L10C2; passage NATP00082.par31 ("Errores autem" continues Corollary 1's errors); witness De Motu Corporum (Liber Primus) (1713); URL https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00082#par31; status implicit_dependency; confidence medium.
- P1713.Law2 → P1713.L10C2; passage NATP00082.par31 (errors proportional to the forces); witness De Motu Corporum (Liber Primus) (1713); URL https://www.newtonproject.ox.ac.uk/view/texts/diplomatic/NATP00082#par31; status editorial_interpretation; confidence medium.
-/
/- LATIN BEGIN NATP00082.par31
Corol. 2. Errores autem qui viribus proportionalibus ad similes Figurarum similium partes similiter applicatis generantur, sunt ut vires & quadrata temporum conjunctim.
LATIN END NATP00082.par31 -/

namespace Principia1713.LemmaX
open NewtonLimitDynamics NewtonLimitDynamics.Fraction

/-- The 1713 normalization from this edition's Lemma X premises. The
coefficient `k * f` is the supplied reading of the proportional forces. -/
theorem corollary2_error_normalized (e : Fraction → Fraction) (k f : Fraction)
    (hk : positive k) (hf : positive f)
    (p : Principia1713.LemmaXPremises magnitudes (ratio e) (mul k f)) :
    QuadraticInitialDeflection magnitudes (fun t => quotient (ratio e t) f hf) k :=
  ⟨hk, ultimate_target_congr
    (ultimate_quotient f hf (Principia1713.lemmaX_reconstruction _ _ _ p))
    (by unfold equiv quotient mul; dsimp only; ac_rfl)⟩

/-- Two errors generated by proportional forces at proportional times share
the positive ultimate value `k` after division by force and squared time. -/
theorem corollary2_errors_jointly (e₁ e₂ : Fraction → Fraction) (k f₁ f₂ r : Fraction)
    (hk : positive k) (hf₁ : positive f₁) (hf₂ : positive f₂) (hr : positive r)
    (p₁ : Principia1713.LemmaXPremises magnitudes (ratio e₁) (mul k f₁))
    (p₂ : Principia1713.LemmaXPremises magnitudes (ratio e₂) (mul k f₂)) :
    QuadraticInitialDeflection magnitudes (fun t => quotient (ratio e₁ t) f₁ hf₁) k ∧
      QuadraticInitialDeflection magnitudes
        (fun t => quotient (ratio e₂ (mul r t)) f₂ hf₂) k :=
  ⟨corollary2_error_normalized e₁ k f₁ hk hf₁ p₁,
    ⟨hk, ultimate_time_scale r hr (corollary2_error_normalized e₂ k f₂ hk hf₂ p₂).2⟩⟩

end Principia1713.LemmaX
